### ISSUE TITLE
[Content section]: width of block component isn't defined by columns, causing containing media width to shrink unexpectedly

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#10049]
### Description

The current content block width is dependent on the amount of content inside. This shows in content section, **when both heading and paragraph contains little content**, width of the component is very small, making the video also very small. This wasn't replicable inside storybook, so this is a screenshot from our build. 

![image](https://user-images.githubusercontent.com/15144993/218511360-c19fb2f2-0a19-4f85-a208-50e3771f497f.png)

### Component(s) impacted

Content section and/or content block

### Browser

Chrome

### Carbon for IBM.com version

v1.28.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

IBM Partner Plus

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

NA

### Steps to reproduce the issue (if applicable)

Carbon for Salesforce's fixed version here for reference: https://c4s-feature-cn-4094-content-width-fix.nnuka7gjzia.us-east.codeengine.appdomain.cloud/?path=/story/dotcom-components-section--content-section-with-video&args=heading:Hellow;copy:World

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by annawen1** [comment]
@shixiedesign so looking at our storybook, it looks like we add specific class to the `children-custom-class` attribute of `content-section` when we use the `content-block-simple`. I was able to replicate the issue in storybook when I removed those added grid classes. 

<img width="1627" alt="Screen Shot 2023-02-20 at 1 05 40 PM" src="https://user-images.githubusercontent.com/54281166/220175562-52e67e9b-07c6-4d85-b0ab-f36969722351.png">

<img width="541" alt="Screen Shot 2023-02-20 at 1 06 56 PM" src="https://user-images.githubusercontent.com/54281166/220175568-2cd4de09-ef94-4d88-853f-434740348010.png">

I believe since the `content-section` has to accommodate other children components, that might be necessary. I'll open up a PR to add documentation for other adopters!
