### ISSUE TITLE
[Tabs extended - with media]: Mobile grid alignment is off when other components are being inserted into the tab content area

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#10298]
**JIRA ticket:** https://jsw.ibm.com/browse/ADCMS-3155

---------------

### Description

- Within the AEM page template, we're currently inserting different layout components (eg. Card Group, Image with caption, Accordion, etc) into the body content area of the `Tabs extended - with media` component.
- The grid alignment looks correct on larger breakpoints, however, it's off by `-16px` on mobile.
- Currently, we have a stop-gap solution in AEM by overriding styling within the shadow root, which is not recommended, but it's a workaround for now. cc: @KDarch928

![Screen Shot 2023-04-03 at 10 46 58 AM](https://user-images.githubusercontent.com/1815714/229897590-81434101-e7f2-4e17-a22b-0e2cb688202e.png)
![Screen Shot 2023-04-03 at 10 47 24 AM](https://user-images.githubusercontent.com/1815714/229897594-3d8c711b-daae-474c-9513-b0c3655fc83f.png)
![Screen Shot 2023-04-03 at 10 47 13 AM](https://user-images.githubusercontent.com/1815714/229897597-165020b2-a028-4df6-b199-b66cb12b81f2.png)

### Component(s) impacted

Tabs extended - with media

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v.1.45

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@oliviaflory FYI ^

@KDarch928 Feel free to add more detail for this particular issue.

**Comment by oliviaflory** [comment]
Hey @proeung thanks for bringing this to our attention

I believe what's happening is that the accordion content area is extending 16px into the gutter on either side, this is to allow some components like cards to hang. 

<img width="663" alt="Screenshot 2023-04-10 at 11 22 13 AM" src="https://user-images.githubusercontent.com/45692622/230932126-0b2f8b62-35ab-4acd-971c-6881550164d9.png">



However, we don't want that with some of the examples your team is using like the Headings and paragraph content on mobile.

I am wondering if this fix should be made in [Tabs extended](https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-tabs-extended--default&viewMode=story) and cascade to Tabs extended with media? 

Another thing to consider is `Tabs extended with media` has the `content item horizontal` component pre-populated and content item horizontal has top/bottom and horizontal padding applied to it in order to align to the grid properly. 

<img width="783" alt="Screenshot 2023-04-10 at 11 15 31 AM" src="https://user-images.githubusercontent.com/45692622/230932649-8c7463a6-fb4d-409f-9513-6d2c04687239.png">


Imagining the final solution will be adjusting the tabs content area

| Current – 16px hang | Desired – no hang |
| --- | --- |
|  <img width="587" alt="Screenshot 2023-04-10 at 11 53 14 AM" src="https://user-images.githubusercontent.com/45692622/230940847-34ffe9c4-3a9d-4181-a158-7b653e22a465.png"> | <img width="585" alt="Screenshot 2023-04-10 at 11 52 58 AM" src="https://user-images.githubusercontent.com/45692622/230940887-6ea39e06-df83-4d17-bff2-053d00df05d9.png"> |

 

----

Lastly, we will be looking into this and other horizontal spacing issues in our Carbon for IBM.com v2 package.
