### ISSUE TITLE
[Date range picker]: The date range picker resets after choosing the start date and clicking on the 2nd box

### ISSUE THREAD

**Issue by AlessandroPomponio** [carbon-design-system/carbon-for-ibm-dotcom#10501]
### Description

When selecting a date range I usually want to select the start date first, and the end date after.

If I have to go back a few pages to pick the start date, however, I’d rather click on the 2nd datepicker box to be prompted with another selector that’s reset on the current date to avoid having to scroll through the pages again.

When I do this, however, the selection gets reset to the first date box, and the only way to do it without having to scroll again seems to be to select the end date first, which feels counterintuitive to me (see video)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/10339005/316e27aa-2c12-45ed-921c-c15944b735b7

### Component(s) impacted

Date picker - range with calendar

### Browser

Microsoft Edge

### Carbon for IBM.com version

v1.27.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

ST4SD

### Package

@carbon/ibmdotcom-web-components, @carbon/web-components

### CodeSandbox example

https://web-components.carbondesignsystem.com/?path=/story/components-date-picker--range-with-calendar

### Steps to reproduce the issue (if applicable)

Refer to video above.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by m4olivei** [comment]
Adding some notes on the history for flatpickr usage as I investigate:

* Flatpickr added prior to carbon web components. See now archived repo https://github.com/carbon-design-system/carbon-web-components for relevant history.
* Flatpickr was introduced at version 4.6.1 with the initial date picker component implementation here: https://github.com/carbon-design-system/carbon-web-components/pull/132
* Note that due to shortcomings with flatpickr at the time, the [range plugin was customized](https://github.com/carbon-design-system/carbon-web-components/pull/132/files#diff-8b60571dea7494fbf22d08813b9fee3ff05a33e322b4d9aec9f2c5932ddbd189). We have carried forward this [customized range plugin](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/carbon-web-components/src/components/date-picker/range-plugin.ts).
* Flatpickr was [auto-updated by renovate from 4.6.1 -> 4.6.13](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9666)
* Flatpickr was then [downgraded to 4.6.9](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10168) due to an [issue that came up](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10088)
* Flatpickr has not had any releases beyond the [problematic 4.6.13 release](https://github.com/flatpickr/flatpickr/releases/tag/v4.6.13) which we attempted but neded to downgrade.

My first thought is to attempt the update to 4.6.13 again, paying specific attention to our customized range plugin. There are a few differences in the Flatpickr imlementation of that plugin between the version we authored our customization against it (4.6.1) and the current version 4.6.13: https://github.com/flatpickr/flatpickr/compare/v4.6.1...v4.6.13#diff-94992f11f9e538e4ecd5aa9e8175b1c462ff5dba0365adabf1d9227c53f02d42
