### ISSUE TITLE
[ToC horizontal] design specs

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#10560]
### Create specs for the horizontal table of contents
Design exploration – #10323

- [x] Review exploration with Jeannie / Olivia / Rich
- [x] Spec chosen option
- [x] Spacing spec
- [x] Color themes 
- [x] Include `@sm` and `@md` annotation (revisit vertical, too)
- [x] Interaction states
- [x] Breakpoint specs

**Comment by RichKummer** [comment]
## Jeannie/Olivia review 06/20/23
The vertical indicator is the favorite styling to explore more deeply. Explore additional options:
- [ ] `16px` vs `24px` horizontal padding for each side
- [ ] `8px` vs `6px` distance from indicator to label
- [ ] Explore hover and motion change (should be simpler than motion explo)
- [ ] Shadow vs border on horizontal ToC. 
- [ ] Inset vs full-width (including beyond `@max`)

- [ ] Circle back with Gower on scroll indicator

**Comment by RichKummer** [comment]
Gower comment to horizontal scrolling:

> Hi Rich, so there are a few considerations:
What visual affordances are there for a pointer user (both mouse and touch) to understand there is additional content
What are the mechanisms to activate/navigate to the additional TOCS items via pointer users? A caution here is that [Pointer Gestures](https://www.w3.org/WAI/WCAG21/Understanding/pointer-gestures.html) requires there to be a method of use other than directional gestures for touch operation. Since you will likely need that for mouse users anyway, it’s not necessarily net new. Note too that [Dragging Movements](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html), upcoming with WCAG 2.2 also places constraints on this. I believe you have this solved in mobile by offering the TOC as a dropdown menu on smaller screens
What are the visual affordances and operators for keyboard users?
As I mentioned, I’d be inclined to think of a carousel-like offering to solve this. You can use the fade to indicate truncation, and then when the user hovers or puts focus on it, there are arrows or something that can get tapped (by mouse) and server as indicators to a keyboard user that there are more items. Note that I don’t think there’s a need for an additional tab stop for these arrows. The arrow cue would be sufficient to indicate to the user they left/right arrow to reposition.
Like a tablist, I’d be inclined to put a focus indicator around the whole thing to clarify the interaction.
Also like a tablist, you need to think about whether the TOC updates the doc position as the user moves between items in the TOC, or when the items are activated

**Comment by RichKummer** [comment]
## Design crit 06/22/23

- Use `16px` left and right padding instead of `24px`. We normally use `16px` padding, and bumping it up here would put it out of sync with similar components.
- Use the `24px` height on the selected state for more emphasis, instead of `20px / text height`
- We'll use the `border` variant instead of `drop shadow`, bringing this in line with other sticky elements like the Masthead
- Extend the full width above `max`, also bringing in line with Masthead.
- Hover can either use the current hover as the safe option, or hint with `$border-subtle-01` as the vertical indicator.
