### ISSUE TITLE
[TOC Navigation Error]: With DotcomShell

### ISSUE THREAD

**Issue by mo-alaa** [carbon-design-system/carbon-for-ibm-dotcom#10821]
### Description

We found a problem with Table of Contents navigation when a Dotcomshell component is used, as shown in the attached videos.
The behavior is as follows for large screens (first video):
- When navigating the TOC from top to bottom, there's some space that becomes hidden.
- But navigating from bottom to top is working perfect.

For small screens (second video) the behavior is exactly the opposite!

This happens with both  `ibmdotcom-react` and `ibmdotcom-web-components`.

We are using TOC from `ibmdotcom-react`, 
Do you think there's a workaround for that behavior?

### Component(s) impacted

TableOfContents for large and small screens respectively

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/41386480/e9f55866-e855-4d39-8f4a-61e2c9a1197b

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/41386480/9d454474-d0c7-4709-8372-e9e00b31623e

### Browser

Chrome

### Carbon for IBM.com version

@carbon/ibmdotcom-react: "1.47.1" | "@carbon/ibmdotcom-web-components": "1.32.0"

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

ibm.com/impact

### Package

@carbon/ibmdotcom-react, @carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/p/sandbox/masthead-web-components-ms797t?file=%2Fwebpack.config.js%3A22%2C5

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by mo-alaa** [comment]
Just a heads up, any update on this one?
Thanks!

**Comment by jkaeser** [comment]
I believe the problem here is that the [`_handleUserInitiatedJump` method](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/table-of-contents/table-of-contents.ts#L398-L446) only accounts for the Masthead's height when scrolling up. It looks like that made sense at the time, but something has clearly changed over the years to where we need to check while scrolling down, too.

This approach is also more brittle than it needs to be, since elements other than the Masthead can be stuck to the top of the viewport (e.g. Leadspace Search). We have a [StickyHeader utility](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/utilities/src/utilities/StickyHeader/StickyHeader.js) that manages all of these and reports the combined height of all stuck elements via the `--c4d-sticky-header-height` CSS prop on the document root element. We may be able to resolve this issue by consulting that value in the `_handleUserInitiatedJump` method.
