### ISSUE TITLE
IBM Logo gets cropped off when rendered through mobile

### ISSUE THREAD

**Issue by archa-bhandare** [carbon-design-system/carbon-for-ibm-dotcom#1866]
There is an issue we encountered when the user tries to register to IBM through the DNA Mobile App.
The IBM Logo gets cropped off in the display.
![image](https://user-images.githubusercontent.com/62687379/77618838-ff5a3e00-6f5c-11ea-85fb-553ab5c66afe.png)

Mobile App renders the following URL in the webview https://developer.ibm.com/dwwi/jsp/register.jsp
 
The configurations used are :
 buildToolsVersion = "28.0.2"
 minSdkVersion = 16
 compileSdkVersion = 28
 targetSdkVersion = 27
 supportLibVersion = "28.0.0"
 
This issue is reproducible only for devices with display sizes bigger than 6 inches.

Please guide on what could be the reason and the solution

**Comment by RobertaJHahn** [comment]
Seems as if this is happening on the web view, so it would be difficult to replicate.  Can you send details about how the application is built?  What is the web view render engine?  Since we don't support any testing in a web view container inside an application.  Can you investigate a fix and contribute it for us to review?

https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/.github/CONTRIBUTING.md

**Comment by RobertaJHahn** [comment]
No response.  Closing
