### ISSUE TITLE
Component: CTA - Screen reader - Play icon information on card is not read for screen reader user.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#2728]
## Detailed description

Issue :- Visually there is a play icon present near the link indicating this link opens a video. But the same info is not available for the screen reader user.

Expected :-
Convey the same info for the screen reader user as well. This can be done by adding the text "plays video" along with the link text /label.

**Comment by kennylam** [comment]
@Praveen-sr Adding copy such as 'plays video' is challenging since this would need to be translated, and not enforceable by us since we can't control what copy is used for the link. This is the same issue for all links that play video or open the url in a new page/tab.

Maybe one solution would be to provide an `aria-label`/`title` for these types of links as props, using `us-en` as the default. Users would could then add copy in whatever language is needed and the responsibility of providing the translation is theirs.

@jeffchew @asudoh @annawen1 @ljcarot Thoughts?

**Comment by Praveen-sr** [comment]
@kennylam Aria label can be used if there is an interactive element like a link or a button. Because Screen reader generally do not pick the aria label on non-interactive elements. If it is an image tag, providing alt text for the image would be a better solution.

**Comment by kennylam** [comment]
> @kennylam Aria label can be used if there is an interactive element like a link or a button. Because Screen reader generally do not pick the aria label on non-interactive elements. If it is an image tag, providing alt text for the image would be a better solution.

@Praveen-sr I was talking more about putting the `aria-label`/`title` on the link itself and not the play icon. or even the CTA link. But yes, it would be on an interactive, tabbable element. As a prop we could default it to English, while still allowing users to override in the required language.

@jeffchew @ljcarot @andysherman2121 Thoughts?

**Comment by andysherman2121** [comment]
@kennylam I agree, this is definitely the best solution I can think of. This would give the user the ability to change the prop to whatever language they want. So we don't have to handle any of the translation

**Comment by jeffchew** [comment]
@RobertaJHahn moving this out to the next release.

cc: @andysherman2121
