### ISSUE TITLE
issues in ibm.com react support for dir="rtl" in header and footer 

### ISSUE THREAD

**Issue by yellowdragonfly** [carbon-design-system/carbon-for-ibm-dotcom#3984]
https://chiefdataoffice.slack.com/archives/C2PLX8GQ6/p1600278573123800

Please see the conversation in slack channel

<img width="1384" alt="Screen Shot 2020-09-16 at 3 05 56 PM" src="https://user-images.githubusercontent.com/1641214/93381139-31729b80-f82e-11ea-8a3f-02e167c1f44d.png">

<img width="1382" alt="Screen Shot 2020-09-16 at 3 06 04 PM" src="https://user-images.githubusercontent.com/1641214/93381142-346d8c00-f82e-11ea-8ad7-c71c00fb70f2.png">

#### Additional Information
- Next step to provide an RTL version of the styles kitchen sink and provide support for the RTL styles in the CCS artifact.

**Comment by RobertaJHahn** [comment]
testing URL:  (https://proxy1.marketplace-test.ibmcloud.com/profile/dataprivacypreferences/welcome/ae-ar)

**Comment by RobertaJHahn** [comment]
Jeff has replicated the bug on the NextJS test environment.  The live Search page does not have the same problem in the Masthead.   

 https://www.ibm.com/search?lang=ar&cc=sa

**Comment by IgnacioBecerra** [comment]
@jeffchew Wrote documentation on how to properly configure RTL ( #4157 ). When RTL is active after following the configuration guide, this bug does not occur -- the search bar is properly aligned to the left.

**Comment by RobertaJHahn** [comment]
This is a dup of issue (#4026).  Consolidating the comments and priority discussed in the Oct 13 Adopter issue review meeting here.  

**Oct 6, 2020 comments:**  There are 2 privacy teams.  This bug was opened by the Privacy Preferences team.  

This page created by the Privacy Portal team appears to be working.  https://www.ibm.com/privacy/portal/ae-ar

Tool that that RTL language sites need to use.  https://rtlcss.com/

Jeff will create an RTL NextJS environment to try to replicate the reported issue.

NextJS environment with RTL enabled:  http://ibmdotcom-nextjs-rtl.mybluemix.net/

Jeff also created documentation to guide adopters on the proper implementation steps.
https://ibmdotcom-react-canary.mybluemix.net/?path=/docs/overview-enable-right-to-left-rtl--page

Jeff will create additional documentation for kitchen sink implementation

**Oct 13, 2020 comment:**  Next step to provide an RTL version of the styles kitchen sink and provide support for the RTL styles in the CCS artifact.

**Comment by RobertaJHahn** [comment]
@IgnacioBecerra The duplicate issue (#4026) was discussed in our adopter issues review meeting.  See the October 13, 2020 comment above.  There is some development work to be done to support the RTL version of the styles kitchen sink.
