### ISSUE TITLE
Web Component:  Card - Pictogram component variations 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#4093]
**Corresponding React epic (#4448)**
The web components version will be developed first.  The React version will be a wrapper of the web component.

### The problem
The [default card component](https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-card--default) becomes very plain and repetitive for **landing and gateway pages**, which often feature over 12ish cards. We need a new visual to 

1. add differentiation to cards themselves for easier scanning, and add differentiation between sections of cards so to keep engagement on all links and destinations
2. break up the monotony with visual interest

## Pictogram card

**Summary**

Pictogram card is designed for page navigation. **Cards are restricted to link out to internal URLs only**. This component can be a variation to the [default card component](https://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-card--default), using the same typography but add a custom pictogram. 

**Design and spec** 
Collection link on Abstract: https://share.goabstract.com/96c3a064-a525-47b7-83e7-a89aeee948e2
- [Pictogram card Jan 4, 2021 design specs](https://ibm.ent.box.com/file/760349403349?s=x815734pg1ktgbiavbdhy84hm5dqpjh5)
- [Pictogram card functional specs](https://ibm.ent.box.com/file/749150538784?s=mc7bzb0zkhcpd7us1mdobadrbb683nu1)

**Variations**
— 2:1 aspect ratio, pictogram bottom (default)
— 2:1 aspect ratio, pictogram top
— 4:3 aspect ratio, pictogram bottom
— 4:3 aspect ratio, pictogram top

![image](https://user-images.githubusercontent.com/15144993/96642999-ef3cee00-12f4-11eb-9b79-5ef6d8f79ee5.png)

## Content model

**Pictogram Card:**
- Pictogram (Required) - Choose from dropdown
- Headline (Required) - Simple Text (Max 40 characters)
- Description (Optional) - Simple Text (Max 75 characters) - If provided, description is shown on hover
- URL (Required) - should be restricted to link out to internal URLs only
- Pictogram Alignment (Default = True) - True: Pictogram on bottom. False: Pictogram on top.
- Inverse (Default = False) - False: Not inversed. True: Inversed
- Size (Default = True) - True: 4:3 size ratio. False: 2:1 size ratio.
- Pictogram Color (Required) - Choose from dropdown. Default = Gray

**Pictogram Grid:**
- Pictogram Alignment (Default = True) - True: Pictogram on bottom. False: Pictogram on top. - This overrides all card values
- Pictogram Color (Required) - Choose from dropdown. Default = Gray - This overrides all card values
- Defined Values for all cards - Inverse = False, Size = True
- The above values are defined because at the time we see no need for an inverse pictogram grid or a 2:1 card grid, but want to enable these in the card content model to support future patterns

### Frequently asked questions about this design: 
Q: Should there be arrows to indicate interactivity? 
A: We removed it during yesterday's discussion. The reason is it's clashing with the picto and taking away space for text. The over all card becomes more clustrophobic. Felt safe removing because 1. The cards all have a hover state (and potentially a more expressive hover state with gradient & colors), 2. Card area is large, so hard to miss. 3. we use icon / picto as a indicator for interactivity relatively often (buttons / tiles / accordion)

Q: Should we pick 1 and not have all 4 variations? 
A: Pictogram top or bottom has proven to be useful for different contexts. Picto top allows for better scanning in situ where an image is strongly associated with the content, for example, Industries. It also helps with breaking up the default heading-first design used most of the time. Picto below allows text to lead, provide more precise communication, but harder to scan for returning users and very monotonous and boring by the end as this is a very common design. In conclusion both designs are needed, and should be a toggle for page authors to choose based on context.

**Comment by RobertaJHahn** [comment]
Designs are still being refined.  Scheduling the func specs and design refinement work to the first sprint of 2021 and will move earlier, if needed.

**Comment by mfearer94** [comment]
Content model has been added to this feature request

**Comment by lily-kenney** [comment]
Here's the design specs link: https://ibm.box.com/s/ykv2ukr3twyfx2nrro3rn7ge4iqoz48x

**Comment by RobertaJHahn** [comment]
@photodow As you know, the designs have been posted by Lily.  Wonil has included review of the designs in his design meeting on Friday, Nov 20.  Work to create the func specs is scheduled in the next sprint, Nov 23 - Dec 4.  Please reach out to Shixie and Michael with questions as you are working on the specs.  We'll be in touch to decide when you are ready to present to the engineers for their sizing.  Shixie and Michael should be included in that review meeting.  Thanks.

cc:  @lily-kenney

**Comment by photodow** [comment]
I haven't seen an update from last week's meeting, so I'll just add a quick one here from my perspective.

So we met last Friday to go over the pictogram cards to see how it fits in with the current design system and determine whether we can move forward with it or not. The designs looked great, and everyone saw a need for it. There were some concerns though around adding too many variations of the card, and whether this was a whole separate card or part of our existing one. There were also some concerns about it's alignment to the current card style guide that was released recently and agreed upon by both teams. Because of some of this, we decided to move forward with a trimmed-down version of the pictogram card. Adding the pictogram to our existing card in the bottom left of the card, and save some of the pictogram positionings and hover effects for a later iteration after we've been able to take a look at our cards from a higher perspective. After talking with Roberta and Linda, it sounds as if we will review this pivot with the development team on Monday.

#### Next steps:
 - Move forward with pictogram card MVP adding pictogram to the bottom left of the card.
 - Conduct an audit of existing cards, desired, and needed cards to see how we can scale our cards better to meet the growing needs we're continuing to see. https://github.com/carbon-design-system/digital-design-ideation/issues/184
 - Reach out to Shixie and team to continue to work with them on the next iteration of the pictogram card.
 - Determine if style guid needs to be updated, or iterated on to allow for these types of cards.

@wonilsuhibm @oliviaflory @JennySanchez

**Comment by photodow** [comment]
Added line to account for pictogram from a functional specs standpoint. Probably should reformat the card functional specs in the near future. It's kind of confusing to navigate right now. 

https://ibm.ent.box.com/file/749150538784

**Comment by RobertaJHahn** [comment]
Based on the comments from Jina, the designs were finalized on Jan 4, 2021. See notes included in issue (#4445)   The final designs are in Box here:  
https://ibm.ent.box.com/file/760349403349?s=x815734pg1ktgbiavbdhy84hm5dqpjh5

The additional work to make the changes included in these designs will now be scheduled.

cc:  @jyoon25 @lily-kenney @shixiedesign @jeffchew @wonilsuhibm @ljcarot @photodow

**Comment by RobertaJHahn** [comment]
CECC / ISCEP adopter has another Card - Pictogram feature request that we are moving forward with under issue (#4927 ).  Closing this issue.
