### ISSUE TITLE
Web component - Logo grid - Images(Logo) are clickable, need to be disabled.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4425]
## Detailed description

Issue: Logo grid - Images(Logo) are clickable, need to be disabled. As per specs.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/17fdb65c-ede8-4f91-a3ae-359428b49fb0)

**Comment by Praveen-sr** [comment]
Comment from accessibility - We understood from the dev that the images present here are simple hence they may not need aria-describedby. Instead providing appropriate alt text using alt attribute would be sufficient.

Note: aria-describedby is recommended to give additional context for images for which alt text alone may not be sufficient.

CC: @RobertaJHahn

**Comment by asudoh** [comment]
At [the React canary site](http://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=components-logogrid--default), seems that each image are surround by links and clicking on it leads you to the link `href`.

@wonilsuhibm @oliviaflory Do either of you have any ideas on whether the link should be removed (as this issue asks for)? CC @ljcarot @kennylam @annawen1

**Comment by RobertaJHahn** [comment]
@asudoh I believe we asked in the QA meeting whether 2 issues are needed.  The response must have been that it was not.  My personal preference is that we have 2 separate issues because, as you say, the priorities may be different.  Maybe we should keep this as a single issue for now and create 2 issues in the future?

**Comment by asudoh** [comment]
@RobertaJHahn Either way is fine to me actually - I initially expected that a (separate) issue with React label is linked to this issue or this issue has both React and Web Components labels. I was confused because neither was the case. Adding React was my quick reaction upon finding that the subject of this issue tells that the issue was with React, too.

Given there is a PR only for Web Components, I guess it makes more sense now for this issue to be separated. Thank you for bringing this up and share your thoughts.

**Comment by RobertaJHahn** [comment]
React version created.  issue (#4549).
