### ISSUE TITLE
bug: Footer failling on MS Edge

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon-for-ibm-dotcom#4582]
## Detailed description

Footer doesn't display properly on MS Edge.
MS Edge is still supported: https://w3.ibm.com/standards/web/browser/#Change%20History

![EDGE footer](https://user-images.githubusercontent.com/11738743/100661478-826c3900-3321-11eb-9619-694cfd3685b4.png)

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by IgnacioBecerra** [comment]
Hi @aiproulx, thanks for bringing this to our attention. Currently we support the latest versions of MS Edge. Could you let us know what version of MS Edge are you using? Thanks again!

**Comment by aiproulx** [comment]
Hi @IgnacioBecerra, 
I have included a snapshot of the version that was installed. 
Note, it is the newest version and there is no option to "upgrade".

Instead, a new version was downloaded from here: https://www.microsoft.com/en-us/edge, and from this new version the footer look proper.

Net - I can not provide the steps to recreate the issue. But know it is possible that some users have the latest Edge version installed and experience what I have shown / shared above.

![image (15)](https://user-images.githubusercontent.com/11738743/100805493-bc5e3d80-33fc-11eb-99db-19fede08fe96.png)

**Comment by IgnacioBecerra** [comment]
Thanks for the update @aiproulx!
From the [link](https://w3.ibm.com/standards/web/browser/#General%20Requirements) you included, we do support MS Edge, specifically the latest versions of the browser. We looked into the issue more closely and found that MS Edge has two different "categories", so to speak. 

One based on Internet Explorer (versions 18 and under) and another based on Chromium (70 and beyond). 
We currently only support the new version (>70), as the former is a legacy browser.

The reason why there was no version to upgrade in your browser is because the one you had installed (version 44) was, in fact, "up to date" with the latest version of the _old_ MS Edge, which was last updated around four years ago.

The one you recently installed is the latest, _de facto_ version of MS Edge, which is currently on version 87, I believe. As it's based on Chromium, there should be little to no differences in the rendering of our components.

I hope I didn't make it too confusing. Let me know if you have any more questions!

**Comment by aiproulx** [comment]
Thank you for the explanation.
