### ISSUE TITLE
[Carousel] Discussion about number of 'cards' to be displayed on the page

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4770]
## Detailed description

Issue: Carousel - Discussion about number of 'cards' to be on the page

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/42cd9306-838d-4ea0-ae24-4f21a0086ccb)

**Comment by asudoh** [comment]
@Praveen-sr Thank you for reporting, one question; May I assume that above screen came with changing `page-size` knob?

**Comment by Praveen-sr** [comment]
@asudoh Yes, changed 'page size' to 4 on knobs.

**Comment by oliviaflory** [comment]
During the QA call a question arose _"How many cards should display at once within the carousel?"_

We labeled as a "bug" in order to get a review/discussion started.

---

I believe the original design intended the cards within the carousel to always align to the 2x grid.
<img width="1348" alt="Screen Shot 2020-12-23 at 12 26 20 PM" src="https://user-images.githubusercontent.com/45692622/103022507-18a70f80-451a-11eb-813a-32ada7dfc67d.png">

Therefore we would not want 5+ cards like this example in the storybook because it will not align to the columns:
<img width="1256" alt="Screen Shot 2020-12-23 at 12 27 48 PM" src="https://user-images.githubusercontent.com/45692622/103022580-4b510800-451a-11eb-805e-16e199f423f1.png">


There should be some logic set for the smaller breakpoints so that we don't allow users to have 4 cards within the medium breakpoint like the example Praveen shared above.

Medium should be 2 cards/images:
<img width="725" alt="Screen Shot 2020-12-23 at 12 23 26 PM" src="https://user-images.githubusercontent.com/45692622/103022300-b51ce200-4519-11eb-9780-0f0da693da43.png">

Small should be 1 card/image:
<img width="364" alt="Screen Shot 2020-12-23 at 12 23 37 PM" src="https://user-images.githubusercontent.com/45692622/103022338-c49c2b00-4519-11eb-9b5f-84881b40c42b.png">


----
**Other things to consider:**

Although the first iteration has 3 cards displayed at once, my understanding is the Carousel component on it's own is flexible enough to accommodate other items other than cards, like images, and I could see additional use cases for carousel. Here's some examples of other layouts I could see us considering, all within the XL breakpoint (1312):
<img width="1119" alt="Screen Shot 2020-12-23 at 12 17 01 PM" src="https://user-images.githubusercontent.com/45692622/103022170-6e2eec80-4519-11eb-8928-c22d489d0160.png">

@photodow I know you had some [early explorations](https://ibm.ent.box.com/folder/94773996791?s=1dqloxyk7kj3wduwj1tlqr6dgtsokgdq) of Carousel too. Would love to hear your thoughts on this as well!

<img width="831" alt="Screen Shot 2020-12-23 at 12 33 41 PM" src="https://user-images.githubusercontent.com/45692622/103023086-404aa780-451b-11eb-889b-bb6bb03f2bd5.png">

**Comment by asudoh** [comment]
Thanks @Praveen-sr and @oliviaflory for your input. Just wanted to drop a note about how the carousel code "technically" works; The number of cards in a page in carousel is automatically determined by available viewport width by default, 1 for small, 2 for mid, 3 for large as @oliviaflory pointed out. The carousel component allows user to manually change the number of cards, that's what the knob @Praveen-sr fiddled with is for. The knob accepts an empty string where the number of cards goes back to the default (responsive).

**Comment by RobertaJHahn** [comment]
Wonil suggests adding an instruction to the knob for guidance.
