### ISSUE TITLE
Card feature enhancements

### ISSUE THREAD

**Issue by julielc121** [carbon-design-system/carbon-for-ibm-dotcom#4927]
### The problem
_We need cards for our Catalog page which allow the logo/icon to be at the top of the card, with Title text and Subtitle text under instead of in the Eyebrow text_

### The solution
_Allow option to put the logo/icon in the upper left hand corner.  These cards will be clickable and will take the user to the details of the system and allow them to add to their cart._

### Additional information
 _We also need the option to include the redirect to another page icon for the cards which will redirect the user to another site_
 - _https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-card--pictogram_
 

![image](https://user-images.githubusercontent.com/29764506/105101101-9869c080-5a6b-11eb-800c-796096f2d2d4.png)

**Comment by julielc121** [comment]
@joseph.paradiso would also like to allow html in the card description so we can display tags when using filters.  I'll let him explain a bit more.

**Comment by RobertaJHahn** [comment]
This may be a dup of a KC request.  Roberta will check on the status.

**Comment by RobertaJHahn** [comment]
There are new Card Pictogram features that will be developed.  This work is being managed under epic (#4093).   @oliviaflory Could you work with Julie Craft to see whether these new variations will work for the ISCEP / CECC adopter as part of Fireline support?

**Comment by oliviaflory** [comment]
@RobertaJHahn I reached out to Julie via Slack, and will be meeting with their team next week (2/1 or 2/2) to discuss their needs and see if the Pictogram card (+ future hover state) will work for them.

**Comment by oliviaflory** [comment]
### Meeting notes with CECC Portal team, Feb 1

**General meeting notes**
In moving to Carbon, hoping to simplify / cleaner tile 
   - In current portal there is no pictogram/icon on the cards
   - new design moves hover state information on the details page.

Icons
- intent is to provide visual information to point out different offerings by sight instead of having to read all titles
- Will have some filtering

Content:
- Icon, 
- title, 
- sub-title, Sub title could go to two lines.
- instead of having "add to cart" (current portal design), selecting the card will take you to the details page.

Some tiles will take you to a separate page, some tiles will take you to a separate application. So still need the option for 

Mixed content, links and possibly tags within the sub-title. 
Example: need some way to add HTML to include tags
- tag would show up when you select the filter
- can select multiple filters, and could possibly get multiple tags

Question: can we use SVG from the pictogram and icon packages, not all icons and pictograms are available within the sketch library. Answer: Yes! 

## Summary:

### Requirements:
1. High level title and Sub-title that is not a hover, this is important information for the user to see up front.
2. Call to action options: Some tiles will take you to a separate page, some tiles will take you to a separate application. So still need the option for 
3. Option for different CTAs at the bottom of the cards. Some tiles will take you to a separate page, some tiles will take you to a separate application.

### Flexible requirements: 
1. Icons vs pictograms
   - The intent is to provide visual information to point out different offerings by sight instead of having to read all titles. Team is open to using Icons or Pictograms, the current CECC Portal design is using 24px icons, the pictogram card is using 64px pictograms.

2. Tags
Need some way to add HTML to include tags
   - tag would show up when you select the filter
   - can select multiple filters, and could possibly get multiple tags
   - Example: _Tag **will not replace the icon**, this was just a test done by the CECC team to show a tag within a card, the icon was the only place the current card would accept HTML_
<img width="1222" alt="Screen Shot 2021-02-01 at 12 00 27 PM" src="https://user-images.githubusercontent.com/45692622/106493790-9cdca300-6487-11eb-8aff-3d8ecf27a2ae.png">


### Timeline:
Hoping for deploy in the middle of April, 2021, will put place holder for now. 
Need something in the next month (February) 
Going into QA in the middle of March.

**Comment by RobertaJHahn** [comment]
Next steps:  Olivia will work with Wonil to finalize the DDS design proposal and get back to Julie.  Roberta will schedule a follow-up meeting with Julie and team next week.

**Comment by ljcarot** [comment]
@oliviaflory or @julielc121 Since these are not pictogram cards but actually card groups with icons, can we rename this issue just so its not confused with other Pictogram enhancements we have underway. Thanks

**Comment by julielc121** [comment]
Hi Linda, We're flexible on using pictogram cards or card groups (with icons).  I wasn't sure if we've established which one would be the suggested for use based on our requirements.

**Comment by oliviaflory** [comment]
Renamed to _**Card feature request**_ until we determine if it should be updates to Card, Pictogram card or a new variation. 

@julielc121 I hope that re-name is ok for now just so our team isn't getting confused.

As Roberta's comment states, I am putting together some options for small tweaks we'd like to propose to your team to align the styling and will schedule another meeting with your team.

**Comment by oliviaflory** [comment]
Wonil and I met with Julie and her team on Feb 3rd to propose a few design options for their Card and shared specs with the team.

We agreed that the Carbon for IBM.com team does not have the capacity to create a new card variation in time for their intended deploy, so the CECC Portal team will develop a card on their own and contribute it back to the Carbon for IBM.com Library. 

They will potentially reach out to David from the Partner World team to collaborate on a variation of Pictogram Card.

Roberta has scheduled a follow up meeting for Wednesday Feb 10th.

**Comment by RobertaJHahn** [comment]
CECC team to develop the card component and contribute it back to carbon for ibm.com repo

See Feb 10 meeting notes [here](https://ibm.ent.box.com/notes/684946537528)
