### ISSUE TITLE
AEM CMS Request: Extend Content Group Simple with an Image and Video Variation

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#4998]
**Request Description:**
1. AEM Author needs a way to render an image between the H4 content item heading and the Content item copy
2. AEM author needs a way to render a video between H4 content item heading and the content item copy

**Summary:** Extend the currently available (link below) Content Group Simple with two modifications:
1. extending the bx--content-item with an image variaion --> I would update https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentgroupsimple--with-image
2. extending the bx--content-item with an video variation --> I would update https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentgroupsimple--with-video

**Contributors from AEM CMS side are below:**
- Visual design- Stephanie Homan and Kirby Evans
- AEM consultant - Georg Hauser
- Developer. - Greg Johnson
- Tech Point of Contact - Ke Xu
- Program/timeline/dependency management - Sandeep Bahl

**Links**
1. Currently available Content Group Simple is available --> https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentgroupsimple–default
2. Related AEM CMS JIRA story is https://jsw.ibm.com/browse/ADCMS-456

If anything was missed, please let Sandeep Bahl know

**Comment by RobertaJHahn** [comment]
Needs design specs, functional specs, dev and Prod QA.  Raph recommends creating a new component rather than changing the existing components.

**Next steps:**  1)  AEM creates the Sketch and pdf files   2)  Add the topic to the engineering meeting to determine whether Raph's recommendation would be the best approach.  3)  Functional specs are needed.  Determine whether that work will be done by AEM or DDS.  3)  Development and Prod QA needed.  Raph will work on this.

Roberta will convert to an epic to manage the work distribution.

**Comment by RobertaJHahn** [comment]
This a feature that will be delivered in the April release.  video player onclick enhancement.  (#5245 ).  Closing
