### ISSUE TITLE
AEM request to keep card width consistent between two-columned and three-columned card layouts

### ISSUE THREAD

**Issue by kirbyevans** [carbon-design-system/carbon-for-ibm-dotcom#5097]
### The problem
Right now, the width of a card changes between 4 columns and 5 columns depending on the number of cards. When there are only two cards side-by-side the card width spans 5 of the 12 column grid. When there are three cards side-by-side the card width spans 4 of the 12 column grid.
### The solution
The AEM team would like to make this width consistent and have the cards consistently span 4 of the 12 columns regardless of the number of cards in its row.

### Additional information
 [Visual example of request](https://ibm.invisionapp.com/share/97O0VZ0BUEW) (Resources section towards the bottom)

**Comment by sbahl1** [comment]
hi Roberta, any chance, we can get an ETA on this ticket?

**Comment by sbahl1** [comment]
Related AEM ticket is https://jsw.ibm.com/browse/ADCMS-522

**Comment by shixiedesign** [comment]
@kirbyevans could you provide the screenshot or link to the component? Currently, [Card group](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-card-group--default) doesn't do that and keeps cards at 4 column wide. 

![image](https://user-images.githubusercontent.com/15144993/109686089-f3ed9a80-7b4f-11eb-9084-343f1acc9eda.png)

**Comment by shixiedesign** [comment]
Caught up with Kirby over Slack and this is component he's referring to: https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentgroupcards--default

We want to keep above component unchanged because it's actually by design. To achieve 4 col cards, AEM team should use the `Card group` component mentioned above. Kirby said he will follow up with devs.
