### ISSUE TITLE
Define component "variant" and storybook strategy 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5361]
### Problem 

Currently, anything look a bit different can be a story in storybook, while others that look wildly different (via options / knobs) are not given a story. **This is inconsistent and hurts our component's discoverability.** 

### Solution 

1. Design team would work on a proposal
2. Bring to whole team for discussion 
3. Implement 

#### Additional Information
- [Storybook format standard wiki page](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/wiki/Storybook-format-standard)

**Comment by photodow** [comment]
Development mentioned Percy's automated visual regression testing is one of the influencers here. Need to reach out to them and figure out how they determine that's needed and when it's not.

**Comment by shixiedesign** [comment]
Initial proposal 

### Component 

A component lives in the root of Storybook left nav (what does that really mean in dev world?)
A component always have a default story in Storybook 

**Example**

> Lead space

### Variant 

**Definition**
A variant is a component with modified knobs/options. These options are build into the component and a variant doesn't introduce new code. 

**Example**

> Lead space - default
> Lead space - with image

**Comment by photodow** [comment]
Some background, context, and initial thoughts...

We didn't really start using the word variant up until we started adding components at bulk onto the [website](https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/link-list#variations). The website I've been told treats a variant based on whether it's a sub-story of the component on Storybook. So there may be 100 different variants, but because Storybook only shows 3 of them the website will only show 3 of them.

Because of the automated testing option, and development kind of adds these in as they see fit for the time being I think we need to be more intentional with our variants on the website, if not also the sub-stories and knobs as this issue is also asking for.

We also have something called a decorator that we at least use internally when talking. The way we've used this in the past is when we want to lock down a specific opinionated or scoped variant of a component and package it up for distribution to our adopters. Decorators tend to get a name, while variants probably shouldn't. Sometimes we'll also add or remove specific elements/features or styling unique to that given decorator.

![image.png](https://images.zenhubusercontent.com/5898a60e51aa2c3057739766/92de141a-09a7-4c1d-973a-01c22b1ca5c9)

**Comment by photodow** [comment]
> Component
> A component lives in the root of Storybook left nav (what does that really mean in dev world?)
> A component always have a default story in Storybook

What are we proposing here? Not a definition of a component, right? This is a strategy for storybook, and what lives at the parent level within the information architecture, right?

Do we see anywhere this is broken today? Maybe `Card section — with images`, and `Card section — simple`?

What is `default` here? In my opinion, it's the minimum options and content needed to render the component?

> Variant
> Definition
> A variant is a component with modified knobs/options. These options are build into the component and a variant doesn't introduce new code.

I think minus some semantics and wordsmithing you and I are on the same page on what a variant is overall. Small things like `knobs` is very specific to Storybook, and probably shouldn't be the official language of our design system.

Maybe something like this...?

> **Component variant**
> A component variant is a form or snapshot of a given component determined by its content and functional options.

A button with an icon and a button without an icon are both variants of a button. A button with the text "open", and a button with the text "close" are both variants of a button. A component in Storybook might have a couple of different variants demoed in separate stories, but that's only 2 or 3 of the 100+ possible variants for that component. Knobs within Storybook are a better tool for seeing all the possible variations a component has to offer.

I want to be clear I'm not proposing storybook knobs should reflect every single option a component has necessarily. In my personal opinion, every component should be designed in Storybook. From how it is played out on the page to what variants we pull out to demo separately, to what knobs are present within each story. I say this because it is apart of the user journey for both designers and developers and should be thoughtfully designed for what their needs are keeping in mind where they've just come from as well as it relates to the website.

More thoughts to come...

**Comment by photodow** [comment]
Reached out to Jeff yesterday for some clarification on background on how they decide to create a sub-story vs. using knobs for regression testing through Percy. One thing he mentioned is that they originally did a span of work to create sub-stories in place of knobs to reduce some of that complexity. He said he found when they did that they discovered the hidden benefit of having sub-stories for that regression testing. As of today they kind of fell into this, and don't have a hard clear rule around when to break it out.

**Comment by shixiedesign** [comment]
Making progress. Update: 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/d258c99d-5eca-41e6-b321-bfeb8b94fa5f)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/e4870afa-d619-4983-894d-71691a25399a)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/8f9c745e-945e-4e11-8573-64ab57b95b9d)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/16ac4ebc-cbe9-4a66-8976-47dc9b4326b8)
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6020c6ea-290a-43b5-ad4e-33fded7ad613)
