### ISSUE TITLE
React: Back to top - Must have placeholder content redesigned 

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5428]
## Detailed description

Issue:
On react and web component - Back to top - Table of content must be removed 

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/d6245973-201c-4a6c-832e-ceddfdd6587d)

**Comment by shixiedesign** [comment]
Hey @kennylam would something like this work? If so I can spec it out. Unless I'm mistaken these should be only using existing components. 
![Solutions | Linux (1312px_xlg).png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/6b10f2bf-a353-48cc-8dd8-ca611382acea)

**Comment by kennylam** [comment]
@shixiedesign Thanks so much for this. Yes. This should work. And yes, ideally they would all be existing components.

**Comment by shixiedesign** [comment]
@kennylam Sample page ready for implementation! 

Design is roughly unchanged from above, details below: 

Content: https://ibm.box.com/s/0vxpecvmx03botdyqxyllvmef2j171ir
Image assets: https://ibm.box.com/s/zvgxjzaacqlxta806e7g3gmn70356wta

**Comment by shixiedesign** [comment]
### Updated the placeholder content so that React wrapper won't freak out: 

Boxnote for easy copy+pasting:

https://ibm.box.com/s/0vxpecvmx03botdyqxyllvmef2j171ir

**PNG** 

![Back-to-top-placeholder.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/11e953d1-6001-401e-8a83-7ab1d63aadf5)
