### ISSUE TITLE
Content Block Cards overwrite bx--content-block

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#5449]
## Detailed description

In Content Block Cards when we use the bx--content-block for spacing above and below component the spacing gets overwritten from the Content Block Cards component on all breakpoints. MD Breakpoint has now a different spacing then bx--content-block in other components. 

> Is this a feature request (new component, new icon), a bug, or a general 
> issue?
Bug

> Is this issue related to a specific component?
Content Block Cards

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The spacing for bx--content-block should not be overwritten in components but a global value only

> What browser are you working in?
Edge, Firefox, Chrome, Safari

> What version of Carbon for IBM.com are you using?
0.15

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM CMS GoLive in April/May

## Steps to reproduce the issue

1. Add Content Block Cards
2. Add bx--content-block wrapper inside

## Additional information
<img width="1699" alt="Screenshot 2021-03-11 at 13 51 25" src="https://user-images.githubusercontent.com/3725699/110790110-ed0e0880-8270-11eb-8d2d-626fac3deaf0.png">

**Comment by RobertaJHahn** [comment]
Raph and Andy will handle as part of the AEM consulting away mission.

**Comment by kennylam** [comment]
hi @skycryer, I think the issue is wrapping the inner content in another `bx--content-block` container. All `dds--content-block-*` patterns come wrapped in `bx--content-block`, so adding it again would affect the spacing. Currently `bx--content-block` is an internal pattern and not meant to be used outside of the components which inherit it.

![image](https://user-images.githubusercontent.com/909118/111360368-09d88080-8663-11eb-81f0-0aa43f9b8ecf.png)

**Comment by skycryer** [comment]
Seems to be solved
