### ISSUE TITLE
Determine what initial audits to provide for Beacon MVE

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5625]
#### User Story

> As a `[user role below]`:
IBM.com application product owner

> I need to:
understand which buckets of tests will be run on my IBM.com application

> so that I can:
understand what level of compliance my application is in regards to those buckets and what are my next steps if any

#### Additional information

 - Have an initial spreadsheet to start from: https://ibm.ent.box.com/file/781913763996?s=dlqitxom2ohulk28htzno3dnoxhvqcka
 - Need to define the buckets
 - Start listing individual tests to run
 - Sizing of severity for items (L/M/H)
 - Preliminary weights for items

#### Acceptance criteria
 - [ ] Clean up the spreadsheet to include the MVE list
 - [ ] Buckets defined with identified individual tests for each bucket (including severity and weight)

**Comment by photodow** [comment]
For what it's worth here are a list of rules I've been documenting since mid last year. Some are easier than others, so obviously we could use that as a measure of prioritizing. I have a few comments and questions and thoughts around how to grade them, maybe some algorithms, weights, documentation or helpful hints and more. It was preliminary, but we can definitely take it further. The list is broken down and somewhat in the order I would prioritize.

One way I was looking at bucketing them was something like this...
- IBM Design Language
- Carbon
- IBM.com Library
- IBM Security
- Cloud Pals
- ... any additional carbon pals
- Custom

Most rules under IDL and Carbon will cover most of the needs in other partners, and I figured those would make a good baseline to start with, and then we could add other teams' needs on top of it as the need arises

https://github.com/carbon-design-system/devtools/issues/13

For IBM.com Library specifically I have a much smaller list I was planning to go out the door with, but it was also a work in progress.

https://github.com/carbon-design-system/devtools/issues/12

**Comment by photodow** [comment]
I think it would be good to take a look at our user's needs and do some EDT around this. Something like big ideas and a prioritization grid might help us get to a list of rules we can start with.
