### ISSUE TITLE
Video player - override enhancements

### ISSUE THREAD

**Issue by aiproulx** [carbon-design-system/carbon-for-ibm-dotcom#5642]
Before the movie is started, support an image to overlay the video.

### Image overlay problem
Missing the support of poster image override.

#### The solution
Example: https://www.ibm.com/cloud/paks

Support:
**data-videodisplay="overlay"**
**src="//1.cms.s81c.com/sites/default/files/2021-02-01/ai-powered-software-to-advance.jpg"**

```
<a class="v19-play-icon-gray-60 ibm-video-player-con ibm-video-placeholder ibm-widget-processed ibm-duo-play ibm-duo-play--relative" data-widget="videoplayer" **data-videodisplay="overlay"** data-overlayplayersize="xlarge" data-showimageplaybutton="true" data-videoid="1_yo72ni9b" data-showvideoduration="false" data-videotype="kaltura" href="//mediacenter.ibm.com/id/#1_yo72ni9b" aria-label="MediaCenter - 
  Play Icon
      " data-kaltura-fallbackid="" data-wow-delay=".2s">
          <div class="ibm-duo-u--ratio--sixteen-nine">
<span class="ibm-play-link"></span><img loading="lazy" **src="//1.cms.s81c.com/sites/default/files/2021-02-01/ai-powered-software-to-advance.jpg"** alt="IBM Cloud Paks: AI-Powered Software to Advance Digital Transformation" class="">
      </div>
   
          <span class="ibm-play-link">
        <svg id="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
  <title>Play Icon</title>
  <path d="M7,28a1,1,0,0,1-1-1V5a1,1,0,0,1,1.4819-.8763l20,11a1,1,0,0,1,0,1.7525l-20,11A1.0005,1.0005,0,0,1,7,28ZM8,6.6909V25.3088L24.9248,16Z" transform="translate(0)"></path>
  <rect width="32" height="32" style="fill: none;"></rect>
</svg>
      </span>
      </a>
```

----

### Caption override problem
The caption rendered with the VideoPlayer is generated from the API. Adopters may want to adjust to fit their needs.

<img width="1432" alt="Screen Shot 2021-08-12 at 3 59 13 PM" src="https://user-images.githubusercontent.com/54281166/129261580-9b18f2b3-daed-41b7-aba8-4a58d2d97910.png">

#### The solution
Allow for override of the caption

### Additional information
- We are using the very same video on this page: ibm.com/docs/
- And the video player component does not support image overlay.
- [Image Overlay updated Functional specs](https://ibm.box.com/s/y8py6laddi9jslvxbt30kvinkvfwfalp)
- [Caption override Functional Specs](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Video#1-caption)

**Comment by annawen1** [comment]
@aiproulx we currently do have image overlay for the video player, but it is pulling that image from the image data set in Media Center. Are you saying you would like to pass in your own custom overlay image?

**Comment by RobertaJHahn** [comment]
@annawen1 KC would like to pass their own custom image into the video player.

**Comment by RobertaJHahn** [comment]
Design and technical investigation is needed. Dragos will look at the possible options with Media Center as part of Fireline.  Jerry Ringuette is the OM.

**Comment by DragosRistici** [comment]
### Initial considerations <br>about accepting custom thumbnail <br>images for videos

## Pros

- Gives audiences a better indication of what's expected in the video 
- Raises curiosity
- Can create emotion
- If done right, will usually have a better resolution and image composition
- Autogenerated thumbnails can be very unfortunate looking images (certain frames in motion blur, low res, irrelevant frame, etc)
- With a signature theme, videos can be associated with different campaigns (see example)
<img width="1128" alt="Screenshot 2021-04-02 at 14 54 17" src="https://user-images.githubusercontent.com/48327647/113414327-6b1f8400-93c5-11eb-9152-914479866977.png">


## Cons

- It might need extra specs
- Same video can have different thumbnails on different pages (it could generate confusion)
- A bad thumbnail image can negatively impact the experience


## Status quo

The` thumbnail-url `attribute in `dds-video-player` and `dds-video-player-composite` are meant to be used by the `dds-video-player-container` so it can insert the thumbnail URL from the Kaltura or Media Center environment. (Media Center contact was made and discussions will take place). Right now, it is not meant for custom thumbnail images. 

As a side note, the previous v18 could accept thumbnail images.

(To be continued)

**Comment by shixiedesign** [comment]
So @annawen1 do you know if custom overlay image is possible on our end? If so, design will add it to the feature request work cycle, where we look at pros / cons, spec & guidance. 
I think another con is that if a badly produced video gets a high quality cover image, the viewers could deceived.

**Comment by shixiedesign** [comment]
The feature request makes sense if we look at the use case below. Unfortunately many videos default cover image are NOT a video still, but with graphic & text over lay already. 

**KC's current video player in context:** 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b0cc792c-1b2f-4b50-be50-7dfeeac17d53)

**Desired cover image:** 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/1f0b63d8-390a-441f-bbf9-65dad4e896b2)

**Comment by DragosRistici** [comment]
## Further considerations regarding the implementation of video custom thumbnail images (thumbnail-url) :

### Cons
1. IBM Enterprise Video (Jerry R.) confirms that there is already in place `the ability to add a custom thumbnail in IBM Media Center`. 
2. As per Felipe A., this type of request is normally targeted towards the CMS / Framework.


### Pros
1. Some of the videos in the current IBM Media Center seem to have automatically generated thumbnail images from video frames. Some of them end up being very unfortunate (weak frame, poor quality, auto res). Here are some examples that exist in Media Center: 

<img width="985" alt="Screenshot 2021-04-07 at 12 12 13" src="https://user-images.githubusercontent.com/48327647/113843953-b0b0c800-979c-11eb-9af9-67461ca78f17.png">
<img width="443" alt="Screenshot 2021-04-07 at 12 11 41" src="https://user-images.githubusercontent.com/48327647/113843980-b6a6a900-979c-11eb-9b16-225cdadb5599.png">
<img width="440" alt="Screenshot 2021-04-07 at 12 10 57" src="https://user-images.githubusercontent.com/48327647/113843982-b6a6a900-979c-11eb-8b72-9c4bbe8f729b.png">
<img width="441" alt="Screenshot 2021-04-07 at 12 10 53" src="https://user-images.githubusercontent.com/48327647/113843986-b73f3f80-979c-11eb-926f-15741ee44206.png">
<img width="985" alt="Screenshot 2021-04-07 at 12 10 26" src="https://user-images.githubusercontent.com/48327647/113843989-b73f3f80-979c-11eb-808c-f3ab401322f7.png">

2. When video aspect ratio is taken into consideration, if the player component does not have the same aspect ratio of the video file, the automatically generated thumbnail image could look unfortunate

3. Adopters using older systems (including Drupal) can add their own custom thumbnail image since the beginning.

4. As per Felipe A., many agile-teams from the web practice in Marketing Studio replace the thumbnail for what they believe will engage better within their segment/product

**Comment by ljcarot** [comment]
@shixie @roberta @dragos based on the investigation, let's proceed with feature request to allow overlay image.  Gives the most flexibility to our adopters with the goal of the best possible affect on our users.

**Comment by RobertaJHahn** [comment]
Rather than close this issue, I will convert to an epic.  @shixiedesign Is just the final design and the func spec issues needed on the design side?

**Comment by shixiedesign** [comment]
Adding the feature request from Slack here for reference: 

![image](https://user-images.githubusercontent.com/15144993/114569329-de858900-9c42-11eb-88df-1270df8002ad.png)

**Comment by RobertaJHahn** [comment]
design specs are not needed, functional specs needed.  Then create all dev and QA issues needed.
