### ISSUE TITLE
[Filter bar] Determine name of new component aka "Filter panel"

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#5684]
#### Additional Information
- **See the epic for the overarching descriptions of the work.**
- Design research and exploration issue (#5683 )
- [reference materials]

#### Acceptance Criteria
 - [ ] Conducted discussions with designers and engineers
 - [ ] Documented the new name and updated the issues linked to the `Filter bar` epic  (#5469 )

**Comment by photodow** [comment]
I'm not totally against filter bar. Only concern I feel hear with it is my brain thinks horizontal, but that maybe minimal, and local to me. IBM security calls it a [filter panel](https://ibm-security.carbondesignsystem.com/?path=/story/patterns-filterpanel--default). I almost like that a little better, and again wonder if we should work with them in any of this. I also kind of like the panel instead of bar because that ties it into its intent and relationship with the [carbon 2x grid](https://carbondesignsystem.com/guidelines/2x-grid/overview/#panel-behavior).

`Filter panel`
`Filter bar`

**Comment by shixiedesign** [comment]
Perfecto! FYI @RobertaJHahn `Filter panel` is the new name. Thank you James for thinking through it this sprint!
