### ISSUE TITLE
[Tabs extended with media | Web Components] Video does not play in mobile

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#5801]
## Detailed description

> Describe in detail the issue you're having.

In mobile, the video in Tabs extended with media does not play

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

Bug

> Is this issue related to a specific component?

Tabs extended with media

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Video to play properly in mobile

> What browser are you working in?

Mobile safari

> What version of Carbon for IBM.com are you using?

v1.18.0-rc.0

## Steps to reproduce the issue

1. Go to https://ibmdotcom-web-components-staging.mybluemix.net/?path=/story/components-tabs-extended-with-media--default in mobile
2. In knobs, switch media type to video
3. Open in full screen
4. Click the video image
5. See image disappears with no video playing

## Additional information

![Kapture 2021-04-16 at 12 59 57](https://user-images.githubusercontent.com/1641214/115062265-28c37000-9eb8-11eb-9ed6-8789d2b2f7b4.gif)

**Comment by jeffchew** [comment]
Be sure to cut from the `release/v1.18.0` release branch for this fix.

**Comment by iwhitcomb** [comment]
The problem is here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/54f70fe7991f472500fdc9d7077a3ab14e4413a4/packages/web-components/src/components/tabs-extended/tabs-extended.ts#L103

The issue with the tabs-extended component is that we're trying to take the rendered markup from a **BXTabs** object and mash it together with a **BXAccordion**. As far as I know, there's no good, or easy way to do this short of building a new component from scratch which is basically what I wound up doing.

If you look at the structure of the markup...

```
<dds-tabs-extended>
  <dds-tab>Lorem</dds-tab>
  <dds-tab>Ipsum</dds-tab>
  <dds-tab>Dolor</dds-tab>
</dds-tabs-extended>
```

From a programming perspective, we should be able to construct the tabs and the accordion off of the same `<dds-tab>` component(rather than duplicating the content). This is also how it was done with the React component.

I'm using the slot to render the **tab** panes and that works fine: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/f616a446d51dec9991b11330e9ac2b664233eb0e/packages/web-components/src/components/tabs-extended/tabs-extended.ts#L151

I'm also looping over the `<dds-tab>` components to construct the tabs which also works because it's just a plain text string.

However, in order to construct the accordion, I'm looping over the `<dds-tab>` components again and attempting to render the markup inside to generate the **accordion** panes. The problem with `unsafeHTML` is that I'm not properly instantiating the object to get all of the necessary javascript required for the video player to function.
