### ISSUE TITLE
[Masthead] On Mobile, search keyword disappears on click on search icon - DDS Consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5920]
## Detailed description

Issue:
On Mobile, Open search edit field and enter any keyword, On click of search icon,  keyword disappears and does not re direct to results page. 

## Additional information

https://images.zenhubusercontent.com/193129061/06b99400-8a7b-470c-8101-a11c45e2b36e/rpreplay_final1619526702.mp4

----
- Hybrid Cloud developer:  Andy Blum
- HC Jira ticket:
- DDS consultant:   Anna Wen

**Comment by proeung** [comment]
@Praveen-sr Are you seeing this issue happening on pages (eg. https://www.ibm.com/partners/) where the Masthead is integrated? Just wanted to see if this is happening just on the Storybook preview or not.

@annawen1 Correct me if I'm wrong, but are we looking to have the search bar redirects to search results within the Storybook preview?

**Comment by annawen1** [comment]
@proeung yes I believe so, on click of the search icon, the behavior should be the same as if the user clicked on a search result from the results dropdown.

**Comment by Praveen-sr** [comment]
@proeung Hi, tested this same scenario on  https://www.ibm.com/partners/ link, its the same behavior as in storybook.  Issue present on partners page.

![SearchKey.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/8faeb2f5-6547-4a5d-80b2-dea0ec0fbd32)

**Comment by RobertaJHahn** [comment]
@annawen1 I assigned this ticket to you as it seems that HC has been reaching out to you on it.

**Comment by andy-blum** [comment]
I've found the source of this and should have a solution tomorrow 🤞

**Comment by andy-blum** [comment]
Just had a call with @annawen1 and here's some additional background:

This issue is caused because some browsers don't pass focus directly to the the button element when it is clicked. Because focus leaves the text input element and _doesn't_ go to the button, it falls back to the body element. This kick's off the component's [focusOut Event Listener](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts#L246-L255)

I've created a basic [codepen](https://codepen.io/andy-blum/pen/XWgKQEm) where you can test this out. Even if we assign the button focus onClick or onMouseDown, the component has already lost focus and closed. The entire sequence of events is:
- user types in search keywords
- user interacts with button, dropping focus back to body (focusOut handler queues in the event loop)
- user completes the click (click handler queues in the event loop)
- focusOut handler clears the form and closes the component
- click handler opens the component

The best solution I can think of right now is to wrap the button in a div with `tabindex="-1"`. In some preliminary testing, this div catches the focus preventing the focus out. We'll obviously want to test this extensively, but i'm hoping it works consistently across browsers and devices.
