### ISSUE TITLE
Expressive theme sunset

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5944]
To track tasks related to sunsetting expressive theme, and redirect adopters to new guidance on how to create an expressive experience using the correct Carbon components.

**Comment by JennySanchez** [comment]
**Note:** PR 1002 has the initial draft content of the updates we need to make on the website (see pages listed below).

- Get started page
- Designing page
- Developing page
- Resources page
- FAQ page

👉 [Task issue #946](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom-website/946) will be closed since the purpose it to get the draft content ready in a PR. 
👉 [PR 1002](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/pull/1002) will remain open till we are ready to finalize the content and merge it to the live website in July.

FYI: @shixiedesign @oliviaflory @RobertaJHahn
