### ISSUE TITLE
[Lead space] Functional spec update to include Breadcrumbs 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6181]
Func spec issue from feature request #6160 

Allowing breadcrumbs as an alternative to Tag group

Below is copied from Slack from James: 

```
This is what we want…
— Carbon breadcrumbs / Tag group (optional)
— Heading
— Copy (optional)
— Button group (optional)
```

**Comment by DragosRistici** [comment]
James and I will update it.

**Comment by DragosRistici** [comment]
The updated functional specs [are in this Box folder](https://ibm.ent.box.com/folder/94761007991?s=d9jey3rlfxqmxu059f0x9dtcx7f5ehuh).

**Comment by photodow** [comment]
Saw a comment that we need to update the wiki for this ticket.

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/commit/10a0a9f06203a5bfabd71caa78db183cdaafa8e3#r51570965

**Comment by photodow** [comment]
Mostly only two or three comments here, the last one is more of a comment as we move forward...
- Need to update the file name with the proper version number
- Missing logic. Only tag group or breadcrumb can be present at once. Might combine 5 and 6 into the same line item. Something like parent navigation (optional) if present either tag group or carbon breadcrumbs.
- `The Current page item in the breadcrumb trail is optional.` This is functionality from Carbon breadcrumbs, right? We might not need this logic if that's the case.  


---

- The visual isn't always needed in these. It's probably fine for now, and no reason to rework it since it's there, but it makes the page longer and makes maintenance harder sometimes. I also have in the template a section for smaller visual examples that might work for a scenario like this when we just want to share what it visually could look like. I usually point them to visual specs for updated visuals though.

**Comment by DragosRistici** [comment]
Done. Thank you, @photodow, doc was updated.
