### ISSUE TITLE
[Layout] component design & spec

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#6253]
### Problem
- Website guidelines on layout https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/guidelines/layout
VS our current layout component in [Web component](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-layout--default) & [React](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-layout--default) are very different. 
- This means adopters who are reading the site, would think they can achieve layout xyz, but lack have specific guidance & example on how to achieve it.
- We need to enable adopters to do layout successfully on their own
- This is part of the initiative to encourage adopter assembling their own layout components, & self serve

Also exist is Wonil's previous content on Layout for Dotcom 
https://ibm.ent.box.com/notes/734766657395?s=1lm1zs6zcof4epd5k9i7wbk00o82glsj

**Comment by oliviaflory** [comment]
## Meeting notes
**Attendees:** 
- Gui 
- James 
- Olivia

### Goals
- Why are Web components and React are different (see storybook links in issue)?
- How is Layout used in our Carbon for iBM.com components
- Discuss intent of Layout for adopter use

### Differences
**React**
- Layout is a component in React
   - React shows the nested feature 
      - Can nest a 2:1 (8col:4col) within the 3 of a 1:3 (4col; 12col) layout
- Only content block and table of contents is using `layout`
   - Content block uses it to get the border, and for the aside elements
   - TOC uses it for the sticky behavior 

**Web components**
- Not exactly a component when we were working on WC version, engineers discussed in engineering channel if we should move forward building layout or just use the mixins from Carbon
   - WC is only using 2X grid
   - We just have the story, not the typescript file or anything.
- After Gui dropped, James and I looked at Content block and TOC
   - TOC did not have the layout component
   - Content block did show some of the layout component, suspect the component might not be built, but the CSS classes are still there


**Comments**
Benefits of layout component
- adds nesting ability, which Carbon does not have. The Carbon 2x grid comes with margin, which the layout component removes so that everything can be lined up on the grid the way we want.
- on top of that, the layout component should allow ability for right to left, so we don't have to swap it every time
- allows adopters to use the same layouts that we are using, and limits the amount of variation.

If we have moved to mix-ins... 
- React needs to follow
- Documentation needs to reflect that as well
- On the flip side, and WC is not using layout, but it needs to use it. Then we need to do a refactor to WC to align it to spec. 
- Should build a WC layout component

Gui used mixins from Carbon for Partner world and Reboot.
- the web builders didn't know how to use 

Clearer guidance 
- how do we present layout component
- how do we document
- how to we show adopters how to use it to build a page

Who is the website for?
- adopters using the components
- adopters building components

**Comment by oliviaflory** [comment]
## Audit Layout guideline page
- how to differentiate between Layout **guideline** and Layout **component**
- identifying outdated content
- Identify which layouts are provided in Layout component vs what is "ok" from grid usage perspective
- [Link to Figma Jam](https://www.figma.com/file/hmUzhVmTPq8vW0qAmMmf92/Audit-of-Layout-guideline-page?node-id=0%3A1)

**Comment by oliviaflory** [comment]
Meeting scheduled for June 16 with Jeff, Shixie and James (optional)

**Comment by oliviaflory** [comment]
### Two types of Layout

**4:12**
- used in the content section components

**8:4** 
- intended to be nested within the 12 of the 4:12 column

It's possible they are making the layouts as they build components, rather than using the layout component

---
- Can we demo the correct layout we want:
   - Create 4:12 and 8:4
   - Need to create more modifier classes to use that
   - Not just making visual adjustments to storybook but we are aligning the component to how the spec is set up
   - Can deprecate (not remove but not document) the modifiers that we don't want people to use (1–3 : 2–3)

- Then we can make the components that need to use layout use it correctly
- How do we align the two frameworks and how it's developed?
  - Get WC straight first: documentation update as a utility
  - React define that it is a utility, we can not advertise that it is a component.

**Comment by shixiedesign** [comment]
Let's discuss next steps during huddle

**Comment by oliviaflory** [comment]
Talked about Layout component in DDS Team Huddle 6/22:

- Provide grid code snippet to accompany the content components (in plain carbon grid language) 
- Layout component is not super useful. 
- Discuss getting rid of the layout components in both react web comp

**Comment by oliviaflory** [comment]
Follow up issue has been created #1082, we can consider this done.
