### ISSUE TITLE
[Masthead] Search edit field - On tab/shift tab, search edit filed is getting closed automatically - DDS consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#6321]
## Detailed description

Issue:
Doing shift tab key navigation from the search edit field, focus moves to the previous element but search edit filed is getting closed automatically.

Expected:
Search edit filed should not get closed until user close it.

## Additional information
-  Engineering info:  
     - HC engineer: @andy-blum 
     - HC Jira Ticket: https://jsw.ibm.com/browse/HC-2192
     - DDS consulting engineer:   Andy Sherman

**Comment by RobertaJHahn** [comment]
@Praveen-sr Could you provide a video of this issue.  Needed for eng to replicate the bug

**Comment by proeung** [comment]
> Search edit filed should not get closed until user close it.

Is that correct? I believe the current behavior is intended by design as you see a similar behavior for the Megamenu dropdown as well. When the user tabs through all of the links, the mega menu closes automatically, which is similar to the search bar, however, let me know if what I'm suggesting is incorrect.

https://ibmdotcom-web-components-canary.mybluemix.net/iframe.html?id=components-masthead--with-platform

**Comment by Praveen-sr** [comment]
@RobertaJHahn Here is the video of the issue,
![Mast1.gif](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/623cfa00-ff0f-4a22-8bb3-d84a3ca5d5a0)

Note: On the react version, Search edit field does not close on tab/shift tab.
