### ISSUE TITLE
[Masthead, React] missing divider between logo and nav items - DDS Consulting

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#6402]
## Detailed description

> Describe in detail the issue you're having.

Seems like the border disappeared somewhere in a recent release 💔  
I'm not positive if this is a styles package or web-component/react fix? Missing in both packages

- [ ] add dividing line between logo and nav items 
- [ ] divider should be hidden if there are no nav items present (see specs)
- [Link to specs](https://ibm.ent.box.com/folder/59063660753?s=mgb8c6urxlvgpfsbxqvqifb1bj9tm6n1)

**Current**
![Screen Shot 2021-06-17 at 1 43 30 PM](https://user-images.githubusercontent.com/45692622/122448064-60ab6a00-cf72-11eb-9aab-efb013e874f9.png)

**Specs** 
![Screen Shot 2021-06-17 at 1 44 49 PM](https://user-images.githubusercontent.com/45692622/122448059-5e491000-cf72-11eb-815f-e5fb41733a3b.png)

> Is this a feature request (new component, new icon), a bug, or a general
> issue?

bug

> Is this issue related to a specific component?

masthead

> What did you expect to happen? What happened instead? What would you like to
> see changed?

add border back in

> What browser are you working in?

Chrome

> What version of Carbon for IBM.com are you using?

[WC Canary](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-masthead--default)
[React Canary](https://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--with-custom-navigation)

----
- Hybrid Cloud developer:   Putra Bonaccorsi
- HC Jira ticket:  https://jsw.ibm.com/browse/HC-2169
- DDS consultant:   Kenny

**Comment by RobertaJHahn** [comment]
Olivia to follow-up.  Maybe a decision was made to remove the divider.

**Comment by shixiedesign** [comment]
Looks like Cloud masthead still has the divider, so is it different divider?
https://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-cloud-masthead--default

If the Cloud masthead PR removed the divider for Dotcom masthead, that's a mistake. There should always be a divider to separate logo from options.

**Comment by proeung** [comment]
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2169

**Comment by proeung** [comment]
@oliviaflory @shixiedesign Looks like the divider line is being applied in the `:before` pseudo-element of the `dds-top-nav-name` component when the platform name is set to true. We have similar styling for the Cloud masthead as well. For the default Masthead without the platform name (eg. Cloud), I think we should move the styling of the divider line from `dds-top-nav-name` and to `dds-masthead-logo` so that it's visible on all variants. 

@annawen1 Let me know if you agree.

![Screen_Shot_2021-08-31_at_3_07_51_PM](https://user-images.githubusercontent.com/1815714/131565436-b35557f6-8636-4705-aa74-1f29d0a31e34.jpg)

**Comment by shixiedesign** [comment]
Please note @RobertaJHahn this issue has to be kept open for React. The bug is only fixed in Web components so far.

**Comment by kennylam** [comment]
@shixiedesign Since it was a change in the `styles` package, it looks like the React version was fixed as well.

http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default

![image](https://user-images.githubusercontent.com/909118/132906368-794e18b4-4247-416f-acac-29d91b425040.png)
