### ISSUE TITLE
[Table of contents] horizontal TOC overlapping content - DDS consulting - AEM dev to fix

### ISSUE THREAD

**Issue by iwhitcomb** [carbon-design-system/carbon-for-ibm-dotcom#6463]
## Detailed description

We're seeing that the horizontal TOC properly attaches to the masthead as you scroll down the page but it the height of the masthead and the TOC navigation causes it to overlap the content within the page.

![ADCMS-1392](https://user-images.githubusercontent.com/887528/123270329-6e5a7580-d4c5-11eb-8df9-78b16b1eb83f.jpg)

## Steps to reproduce the issue

1. Create a page with a masthead and a horizontal table of contents.
2. Click on the items of the TOC to scroll down the page

**Comment by oliviaflory** [comment]
Hi @iwhitcomb, a few follow up questions:

The masthead should scroll out of view so the TOC is the only sticky element on scroll down. 
Are you using the [dotcom shell](https://ibmdotcom-web-components.mybluemix.net/?path=/story/components-dotcom-shell--with-horizontal-toc)? I believe the dotcom shell has that logic built in so the content doesn't overlap, see below:
![TOC-down-Jun-24-2021 11-28-41](https://user-images.githubusercontent.com/45692622/123292726-5690ea80-d4e1-11eb-9526-5d48db1e535c.gif)



I am seeing an issue on the scroll up logic, the masthead is meant to come back into view on scroll up for the user, but because of the double stack the content is overlapping when the user interacts with a previous TOC item. 

I'm chatting with the team now to come up with a solution for `scroll up` fix.
![TOC-up-Jun-24-2021 11-29-54](https://user-images.githubusercontent.com/45692622/123292755-5d1f6200-d4e1-11eb-851d-b74ed1142513.gif)

If you could provide any info on upcoming release dates for your experience, that would be great, thanks!

**Comment by ljcarot** [comment]
@RobertaJHahn per slack today, HC engineer will be picking up this bug to work on this sprint (Jul 7). I asked them to let us know who.

**Comment by proeung** [comment]
@huntermacd is the HC engineer that's assigned to this ticket. Hunter, please reach out to @iwhitcomb or @ariellalgilmore if you have any questions about this bug ticket.

HC JIRA ticket: https://jsw.ibm.com/browse/HC-2078

**Comment by proeung** [comment]
Disregard my message above. This issue has been reassigned to @andy-blum, a new FE dev from the HC team.
