### ISSUE TITLE
Tabs extended - Tab content is placed in shadow dom on mobile

### ISSUE THREAD

**Issue by dratzenboeck-ibm** [carbon-design-system/carbon-for-ibm-dotcom#6549]
### The problem
On mobile the tab content is moved to the shadow dom, so I can't override any css there. That means you can never put a component there that is not specifically supported and implemented by you. 

### The solution
The tab content should not be moved to the shadow dom on mobile, so that I can also style it there via overrides. 

### Additional information
AEM Page with tabs component that is trying to override a style for horizontal group inside tabs extended:
https://dev-publish.np-roks.cms.cis.ibm.net/daniel-test/new-solution-page . The heading of the horizontal group has too much spacing that's why we needed to override it. But we can't on sm / md breakpoints.

**Comment by RobertaJHahn** [comment]
Shixie will investigate whether a short term solution is possible.  A more thorough fix will require a refactor of this component.

Will decide how / when this will be addressed after Shixie investigates.

**Comment by shixiedesign** [comment]
Hi @dratzenboeck-ibm we are looking into this. It seems like to fully resolve the issue it would need a refactor of the component. Here are a few quicker solution through using different content & component. Are any of the follow acceptable for your use case? 
- Remove the `First Tab` headline. There's already a headline for the content inside. It's best to avoid multiple headlines for one element
- If you intend to have more than one element inside the tab, keep in mind if the tab content extends below the fold, tabs will scroll out of view. Again, best to avoid because users would have to scroll back up to click on other tabs. This decreases discoverability of other tabs' content

**Comment by dratzenboeck-ibm** [comment]
@shixiedesign Thank you that are very helpful hints. Need to align with the team on that. Maybe we need to adjust our tab component stories. 
Some more questions as we currently have a specific requirement for a tabbed cta block. Is the CTA Block supported within the tabs? Or would that also need that refactor you mentioned? Or would you rather prefer our design team to request you to enhance the tabs extended component in advance whenever we want to add different components in there?

**Comment by shixiedesign** [comment]
Hi @dratzenboeck-ibm sorry for missing this. CTA block should be supported within Tabs extended. It should simply have a child container and any component can be passed in! If that's not working, definitely lemme know and we will look into it as a bug. 
If it works, but looks not great, then we can make this a feature request and consider a refactor. Thanks!

**Comment by RobertaJHahn** [comment]
Closing as no response from @dratzenboeck-ibm.
