### ISSUE TITLE
[Footnotes section] design exploration

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#6706]
**Note**: consider getting started on this task this sprint, but not expected to finish.

### Task

As an adopter of Carbon for IBM dotcom, I need to have a section just above the footer so I can add there the page references and footnotes. When you are using statistics, you need in most of the cases to add footnotes at the end of the page.  [This is an example](https://www.ibm.com/cloud/paks?lnk=ushpv18l1) that comes from the US homepage and uses reference links and also extra notes in plain text. Right now, adopters are using a very small type, also disregarding a max number of characters per row. This should be considered from a legal and also an accessibility perspective. 

<img width="1620" alt="Screenshot 2021-07-21 at 21 27 24" src="https://user-images.githubusercontent.com/48327647/126540669-e2c0dac4-0284-420c-ac08-2601ad681538.png">

<img width="1748" alt="Screenshot 2021-07-21 at 21 26 23" src="https://user-images.githubusercontent.com/48327647/126540530-8e28dabe-b25c-46c6-b34a-6c6f68c54ef6.png">

**Comment by shixiedesign** [comment]
Hey @DragosRistici checkout this [footnote design](https://ibm.box.com/s/0uj726owdvd6pomfqnyd6p5fzksw9uyn) from Wonil and Jina awhile back. It was not developed because we were not sure about accessibility requirements. 

In general I agree the footnotes seen in some current pages are terrible. This issue can be turned into an epic and when we have bandwidth, we can continue this component.

**Comment by jeffchew** [comment]
This should probably be turned into an epic later, to be sized by design team.
