### ISSUE TITLE
[Lead space] Create or build skeleton style 

### ISSUE THREAD

**Issue by sbahl1** [carbon-design-system/carbon-for-ibm-dotcom#6723]
When Target is used to perform or create experiments in Target on AEM components, the Target team noticed unresponsiveness and delays in load time.  Upon more investigation, the teams found out that we need to add animation to cover the component while Target is personalizing the component for relevant components.  

How? The team intends to use a skeleton on a component. Link is https://the-carbon-components.netlify.app/?nav=skeleton. 

Scope? The request is to add on any component and also at the page level for CMS. We will need to enable this for all components used in all components. 

Web components with element name for example is <bx-dropdown-skeleton></bx-dropdown-skeleton>

**Comment by shixiedesign** [comment]
We will do a bit of investigation to see what's the ideal solution to the problem. From Slack conversation, the problem we are trying to solve really is: 
Target takes a few seconds to serve up customized content. 

Benefits of skeleton state is it helps to avoid page jump. But skeleton state is typically used in products where performance is challenging depending on data queries. This is not usually a challenge in marketing pages, so we have not considered adding skeleton states. 

Skeleton state is also less effective in preventing page jump when content is unknown, for example the content can be 3 lines wrap on that breakpoint, and causing a jump anyway.

**Comment by shixiedesign** [comment]
Hey @sbah1 The design team had a huddle on it and we agreed it’s best to find alternative solutions to lead space skeleton state. Because load time shouldn’t be an issue for majority of our usage cases, and it’s relatively easy to achieve the gray box on your end or hiding content until Target is ready. When some load time is an issue, it’s usually happening in productive experiences, for which the Carbon components skeleton states are available already. If there are more use cases that could need skeleton states in the context of expressive experiences (marketing content, editorial content), please bring it to our attention and we will evaluate again. Thanks!

**Comment by leetsao** [comment]
The skeleton was identified by Shawn Hoglund as a desired UI that was already available in Carbon that should be used as a default loading animation for the Leadspace.  This would be implemented to make all pages have a consistent load in animation for the leadspace so it would be more difficult for end user's to identify if something was altering the page, like Adobe Target.
Other places in the site use other animations like fade in's or the loading spinner but Shawn identified skeleton as the desired state.

**Comment by RobertaJHahn** [comment]
8/30 Engineering meeting summary:

- This fix should not be implemented as a DDS component
- It should be a CSS class with some styles applied on the application side because there is additional work to be done to manage the space.
- DDS dev to provide a code sandbox example (Need a dev issue) Priority - High (no release for this work)
- Lee scheduled time in the 9/1 Engineering Office hours.  This approach will be discussed in that meeting.
