### ISSUE TITLE
Implement Lead space - short

### ISSUE THREAD

**Issue by crichtonibm** [carbon-design-system/carbon-for-ibm-dotcom#6873]
When using the ibm.com UIShell, the medium sized lead space seems to be the smallest supported today.  Our website is not marketing related, and has page refreshes with new content when interacting with forms. The large lead space results in our users needing to scroll to get back to the intended page content with which they are interacting. I am aware that I can have NO lead space, but will result in some lost context, so would like to see a 'short' size

As an ibm.com website developer I would like a smaller Lead space area for the UIShell so that our users can achieve their page interactions without scrolling. 

Adopter:  IBM Customer Connect
Contact:  Joseph Crichton

**Design spec:** https://ibm.box.com/s/mnqx7jzi3vo7ssqaf8oyd3kb8x9mv3p8
**Functional spec:** https://ibm.box.com/s/b0xcd5fncm2424b2dyxlz28u60bmwqsj

**Comment by RobertaJHahn** [comment]
@shixiedesign Can you look at this to determine design's position on this?

**Comment by shixiedesign** [comment]
@RobertaJHahn This already have design specs. Lead space - short is designed to be 320px based on Lara's research. The specs is available here: https://ibm.box.com/s/mnqx7jzi3vo7ssqaf8oyd3kb8x9mv3p8

So this is the last height of Lead space intended by design. This is the full set of left aligned Lead space. Designer is Dragos:

![image](https://user-images.githubusercontent.com/15144993/129731748-503dc5b1-1245-4a82-97fb-15853a8604b1.png)

**Comment by DragosRistici** [comment]
@RobertaJHahn @shixiedesign @crichtonibm The design specs are featuring `Lead space short` of 320px in height (for desktop breakpoints, and free flowing height for smaller breakpoints). It is the last one left to be developed.

**Comment by RobertaJHahn** [comment]
@crichtonibm  Unless we hear from you, we have set this as a Medium priority.
