### ISSUE TITLE
[Layout] Component mismatch between libraries

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#7017]
The Layout component has different Storybook contents, as well as different docs. In React it has its own component, while in Web Components it seems that it only has an HTML layout using the classes from the styles package. To achieve structure parity, it may be necessary to build a Layout component for Web Components.

**Comment by RobertaJHahn** [comment]
Need more informaiton from James.

**Comment by RobertaJHahn** [comment]
meeting notes:
Layout component in React was created in order to apply constraints.  Layout was created before the Carbon grid components existed.  Borders, sticky class and nesting are not included in the Carbon grid.  The layout component is needed if we want to maintain control.  **Decision:**  Layout component is difficult to maintain.  Will deprecate the React Layout component and create a collection of styles by organizing in a mixin.  Update the React layout component to point to the mixins.  The Layout component would become a wrapper for the mixins.

Steps:  convert issue to epic, Update functional specs, include the topic in the Engineering Huddle to define the dev issues, regression testing needed for the defined components.
