### ISSUE TITLE
[Link with icon]: Icon placement not changing

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon-for-ibm-dotcom#7074]
**Engineering info:**  
- Innovation Team engineer: @proeung 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2401
- DPO consulting engineer: 

-----

Describe the issue: 

> What did you expect to happen? What happened instead? 

The Link With Icon's icon placement is not changing if chosen to be on the left, stays right.

> Component(s) impacted? Please include screenshots, or code and relevant URLs.

Link with icon

> What version of Carbon for IBM.com are you using?

Web Components Canary

Steps to reproduce the issue (if applicable):

1. Change `icon-placement` knob to left
2. Nothing changes

**Comment by emyarod** [comment]
just ran into this while working on #6265, I have a potential fix but just need design confirmation on what the behavior should be when icon placement is on the left and text is wrapping, since the icon wraps inline with text when it's placed on the right side (most of the time)

![image](https://user-images.githubusercontent.com/8265238/132412095-fca66ccf-3e09-41df-95ad-401b5c4ef050.png)

![image](https://user-images.githubusercontent.com/8265238/132412187-f9c82f7b-901c-4aa8-bb4c-48a31fecfcb6.png)

related https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5705 https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6812 cc @shixiedesign

**Comment by emyarod** [comment]
this may also be a storybook only issue as it seems to function properly when the icon placement knob is changed and the storybook canvas is opened in a new tab

**Comment by shixiedesign** [comment]
Here's the link with icon text wrapping spec & example. @emyarod 

![image](https://user-images.githubusercontent.com/15144993/133141606-0da77fc2-5d50-41df-872f-8f94ce2d1edd.png)
