### ISSUE TITLE
[Sketch kit] Remove interactive-01 text 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7524]
Currently in Gray 100 theme, type style: productive > body short > 
1. **interactive-01** expecting to be Blue 40, seeing Blue 60
2. **inverse-link** expecting to be Blue 40, seeing Blue 60
3. Shouldn't `link-02` be large, 16px size, therefore not in Productive? It does have the correct color here. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/cb0c2727-f199-43be-89c0-8d1010442d8d)

**Comment by oliviaflory** [comment]
@shixiedesign 
These are actually all as expected and match Carbon's design kits. 

1. Interactive-01 is Blue 60 across all themes. We can remove on the Expressive list if we feel it's not useful. I'm not positive where Carbon uses it, been digging around.
2. Inverse link is used on the inverse color, which is opposite of the theme
3. Link-02 is a token Carbon added for secondary links. We can remove on the Expressive list if we don't want it, but it's possible some adopter might find it useful in the future?

In general, I have been mirroring the body-short-02 color options with the body-short-01 colors that are available with the Carbon kits. I hesitate to limit the kits because they are tools to show the different options that are available in the system, but if there are ones we feel strongly about we can remove from expressive sets.

Because we have both expressive and productive, I'd rather not remove any color options that the productive set has in the Carbon kits.

<img width="1200" alt="Screen Shot 2021-11-02 at 10 31 31 AM" src="https://user-images.githubusercontent.com/45692622/139882999-b9aebb39-78f5-4309-9ac2-c0031711bbf9.png">
<img width="1205" alt="Screen Shot 2021-11-02 at 10 31 48 AM" src="https://user-images.githubusercontent.com/45692622/139883011-e11f418c-7168-4b1f-83e5-34626bff67d7.png">

**Comment by shixiedesign** [comment]
I see... you are right! So then my question is do we need the text in `$interactive-01` color? It's not accessible on $ui-background in the dark theme. Looks like usage is not recommending it for text too.

**Comment by oliviaflory** [comment]
yeah I'm not positive about `$interactive-01` in the text styles, it's in the productive set. But probably safe to remove for our purposes! 

It would be accessible on top of the inverse-02 background tokens..but not sure when you'd need an interactive token rather than the link token?

I can ask Lauren what it's used for too.

**Comment by oliviaflory** [comment]
@shixiedesign I'll go ahead and delete the $interactive-01 from the kits now so we don't release something that is outdated, from what Lauren said it sounds like it's not in use.

> I am kind of thinking we used to use it for button text (tertiary/ghost) and link text, before we had an actual link-01 token. I don't think we are using it anymore for text styles
even the selected state number in date picker uses interactive-04. so i think its just an old thing we used to do

When I was adding the 3 expressive components I saw we were missing `$text-04`, `$inverse-01` and `$interactive-01`, in the expressive set, so I added but will remove now!

**Comment by shixiedesign** [comment]
Cool sounds good! It could have been a left over of Carbon v9, where `$brand-01` was used for text in some UI moments.

**Comment by shixiedesign** [comment]
@oliviaflory I updated the issue title. No rush, but feel free to assign yourself when you get to this. Thanks!

**Comment by shixiedesign** [comment]
TY!
