### ISSUE TITLE
Safari baseline: [Link list section] arrow should be top aligned to text - No DDS consulting

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#7572]
**Engineering info:**  
- HC engineer: @mwanberg 
- HC JIRA Ticket:  https://jsw.ibm.com/browse/HC-2309
- DDS consulting engineer: No consultant

----

Appears to have several issues in Safari: 
- text padding right might be smaller, resulting in less line wrap
- arrows should be top aligned to text, not center aligned 

![link list section.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/28dab016-bb30-4d9b-a37c-c15512e0a321)

Same issue in mobile: 

![Nov-02-2021 14-21-03.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/2755b907-0f03-4e76-a405-342fe9c44dbe)

**Comment by mwanberg** [comment]
@RobertaJHahn @shixiedesign 

Looks like this is caused by a WebKit bug that has bitten us before: https://bugs.webkit.org/show_bug.cgi?id=229438. @jkaeser (who found this bug) put together https://codepen.io/jakaeser/pen/jOLoRdX as an easy way to see it in action. The good news is that it's been fixed, and the fix can be verified in [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/). The bad news is we have no idea when that fix will make its way into regular Safari.

Would you like us to find a workaround or should we wait until the Webkit bugfix is released?

**Comment by shixiedesign** [comment]
Hey @mwanberg so I understood there's a bug here in WebKit that changes the text color, but didn't see how it affected the icon alignment? Do you know the cadence of WebKit releases to have a rough estimate? My thoughts are if it's less than 3 months, we can wait. It's just a gut-feeling number. Happy to hear other opinions.

**Comment by RobertaJHahn** [comment]
@mwanberg Discussed in the Adopter issues review meeting this morning.  The concensus is that we will wait for the WebKit fix and not do a work around.  @shixiedesign This discussion took place before you joined the meeting.  Moving to `icebox` pipeline.

**Comment by mwanberg** [comment]
@RobertaJHahn @shixiedesign Sounds good!

cc @proeung
