### ISSUE TITLE
[Content block] Update type token for content

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/carbon-for-ibm-dotcom#7746]
### Description

It looks like the Storybook for `Content block` is out of sync with the design specs. 

Currently, the Storybook version is using `expressive-heading-01` for the copy directly beneath the block heading, but the design specs indicate the correct type token is `expressive-heading-03`. 

See Devtools:
<img width="1892" alt="Screen Shot 2021-11-23 at 4 53 40 PM" src="https://user-images.githubusercontent.com/15643582/143135913-f026181b-dd04-467d-838f-6efa8e990d2d.png">

See design specs:
<img width="1710" alt="Screen Shot 2021-11-23 at 4 54 11 PM" src="https://user-images.githubusercontent.com/15643582/143135631-ab524c71-8220-41c2-a68a-8d0c847765ab.png">

### Component(s) impacted

`Content block`

### Browser

Chrome

### Carbon for IBM.com version

v1.12.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

C4IBM.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-content-block--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by shixiedesign** [comment]
Potentially fixed here in Gui's PR https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7645

Maybe triage it again after Gui's PR merges.

**Comment by RobertaJHahn** [comment]
Moving to the `To be Triaged` pipeline for review after PR #7645 merges.

**Comment by oliviaflory** [comment]
The type size is correct, but DevTools was identifying it as a `productive` token rather than `expressive` and it's not scaling at all in the [canary build](https://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-content-block--default). 

I'm thinking it might be that we are missing the `expressive-heading-03; true` in [this line in the style sheet](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/styles/scss/internal/content-block/_content-block.scss#L204)

    @include carbon--type-style('expressive-heading-03');
