### ISSUE TITLE
Web component: Dotcom shell - Card with images are not operable.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#7766]
### Description

Issue:
Dotcom shell - Card with images are not operable.
For screen reader, cards are not identified as links.

### Component(s) impacted

![image](https://user-images.githubusercontent.com/60002341/143891261-6f15fe73-8aec-4991-beb6-77d0f02cd986.png)

### Browser

Chrome, Firefox

### Carbon for IBM.com version

1.28

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Web component

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RobertaJHahn** [comment]
@kennylam Here is the dotcom shell Card with images bug we talked about in the meeting earlier today.  If you could take a deeper look to be sure that this issue to confirm that this should not be fixed in an rc, that would be great.  If our suspicions are correct, then remove yourself as the assignee and move the issue into the `Pending scheduling` pipeline.
