### ISSUE TITLE
[Leadspace-with-search]: Missing styles

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#7781]
### Description

When using the `dds-leadspace-with-search` component, there are missing styles that cause the component to have extra padding below the heading and the copy, horizontal rule doesn't appear, and the image variation doesn't show properly either.

This is how it looks when trying to set up in the carbon tutorial application:
<img width="1607" alt="Screen Shot 2021-12-01 at 5 35 47 PM" src="https://user-images.githubusercontent.com/54281166/144325286-98a952b7-91a6-44d1-965e-bf68e8ac6d9a.png">

Notice also that the placeholder in the `leadspace-with-search` is `undefined`. If I remove the `dotcom-shell` import from the application, then it shows up as `Search All of IBM`. 

Branch for Step 2 of the Carbon for IBM.com Web Components tutorial: https://github.com/carbon-design-system/carbon-for-ibm-dotcom-tutorial/pull/2

relevant code:
```
<div class="bx--grid">
    <div class="bx--row">
      <div class="bx--col-lg-8 bx--offset-lg-4 bx--no-gutter">
        <dds-leadspace-with-search>
          <dds-leadspace-block-heading slot='heading'>Find analytics services</dds-leadspace-block-heading>
          <dds-leadspace-block-content slot='content'>
            <dds-leadspace-search-block-heading>Make fast and accurate data-based decisions</dds-leadspace-search-block-heading>
          </dds-leadspace-block-content>
          <dds-search-with-typeahead slot='search' leadspace-search><dds-search-with-typeahead/>
          <dds-hr slot='hr'></dds-hr>
        </dds-leadspace-with-search>
      </div>
    </div>
  </div>
```

Issue is also visible in the codesandbox example:
https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/examples/codesandbox/components/leadspace-with-search

### Component(s) impacted

`dds-leadspace-with-search`

### Browser

Chrome

### Carbon for IBM.com version

v1.12.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/examples/codesandbox/components/leadspace-with-search

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-for-ibm-dotcom/tree/master/packages/web-components/examples/codesandbox/components/leadspace-with-search

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment]
The `undefined` placeholder bug might be due to this line, where the `placeholder` property is using `reflect: true`, which could be causing the strange behavior (more info [here](https://lit.dev/docs/v1/components/properties/#:~:text=If%20toAttribute%20itself%20is%20undefined%2C%20the%20attribute%20value%20is%20set%20to%20the%20property%20value%20without%20conversion.))
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts#L531

By removing `reflect` under the `ES` files under the tutorial repo, I'm able to get it to render properly.
<img width="1448" alt="Screen Shot 2021-12-13 at 2 42 02 PM" src="https://user-images.githubusercontent.com/24970122/145903006-84b4ec86-f44b-483c-9016-ca2699ef3c4a.png">
