### ISSUE TITLE
[Web Components Tutorial]: Design asset for the digital badge

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#7783]
### User story

> As a `[user role below]`:

Carbon for IBM.com Web Components tutorial user

> I need to:

apply for a digital badge

> so that I can:

show that I have completed the tutorial

### Additional information

- Badge design must follow similar look and feel of the existing Carbon badges: https://www.carbondesignsystem.com/developing/react-tutorial/wrapping-up

![image](https://user-images.githubusercontent.com/1641214/144129337-3520b691-3ed9-4ba7-9bb7-59189cd51b2d.png)

- This is blocking completion of the `wrap-up` and badge submission issues
- This is the [design asset](https://ibm.ent.box.com/folder/151482944550) from Carbon team. Note: the type is outlined so we will have to re-create the art in order to edit the type. The type looks like IBM Plex Condensed.

### Acceptance criteria

- [ ] Provide design asset for the Carbon for IBM.com Developer Essentials - Web Components

**Comment by oliviaflory** [comment]
Likely need to look into the [Credly](https://www.credly.com/org/ibm/badge/ibm-carbon-design-system-developer-essentials-react) image requirements for Badges.

**Comment by oliviaflory** [comment]
After speaking with Matt, he asked us to create a badge that would visually align with the current Carbon tutorial badges.

I've done a number of explorations using the existing badges and outlined my thought process below with the ones I think work the best.
<img width="1401" alt="Screen Shot 2021-12-23 at 9 33 59 AM" src="https://user-images.githubusercontent.com/45692622/147257061-649bb169-4c37-46af-ab3b-8f94afc9950d.png">



### Badges for React, Vue and Angular
<img width="1396" alt="Screen Shot 2021-12-22 at 2 17 06 PM" src="https://user-images.githubusercontent.com/45692622/147254922-21e75c77-7031-4ede-b8cb-749f72358d52.png">

![Artboard 1-100](https://user-images.githubusercontent.com/45692622/147255067-cd9e6e15-db2e-42d9-8c8b-b253a1aaa148.jpg)


### Option A
This version would be good to use if we, or the Carbon team, would like to create a Web components version of the Carbon components tutorials, it aligns exactly to the React version, however does not communicate the Carbon for IBM.com piece of our tutorial.
![Artboard 10-100](https://user-images.githubusercontent.com/45692622/147255454-f31738eb-a7f9-4cb0-af46-27b63615935e.jpg)

### Option B
I tried fitting "Carbon for IBM.com Web Components" into the area where the other frameworks are written, but it feels a bit cramped to me and is not my favorite.
![Artboard 9-100](https://user-images.githubusercontent.com/45692622/147255945-756d0969-61d4-4e69-9118-7865a3981af0.jpg)

### Option C
I changed "IBM Design System" in the top portion of the badge to "Carbon for IBM.com". "Web components occupies the same space as "React" in the original badges.
![Artboard 11-100](https://user-images.githubusercontent.com/45692622/147256367-e114b65b-2e7c-483e-a193-29bbb5ba904e.jpg)


### Option D
Same as Option C, but uses a teal color rather than green from the IBM palette. I thought it could be helpful to differentiate it a bit from the IBM Design System badges so the "Carbon for IBM.com" stands out a bit more.
![Artboard 8-100](https://user-images.githubusercontent.com/45692622/147256380-374508b4-5543-46e4-8ec3-3f55cf0dcaf8.jpg)


Here are all the options next to the React version for comparison
<img width="1430" alt="Screen Shot 2021-12-23 at 9 52 59 AM" src="https://user-images.githubusercontent.com/45692622/147256920-f1372f1c-6b26-447f-aaa0-f21fdb4ec74c.png">

**Comment by oliviaflory** [comment]
Final selection:
![Artboard 8-100](https://user-images.githubusercontent.com/45692622/148094288-1013d660-20c6-47b8-8774-86d5cfcfee04.jpg)

[Final SVG uploaded on Box](https://ibm.ent.box.com/folder/151482944550)
