### ISSUE TITLE
[Footer]: e2e test failure: sporadic errors with footer short - DPO Consulting

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-for-ibm-dotcom#7898]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2363
- DPO consulting engineer: @IgnacioBecerra 

----

### Description

The following appears to be happening on certain tests for the footer in Browserstack:

![image](https://user-images.githubusercontent.com/1641214/146444808-17110631-e280-4037-a7fa-3ce2b92a6327.png)
![image](https://user-images.githubusercontent.com/1641214/146444526-b492cbc2-e1b7-4bbb-9848-3da269a10b9f.png)

### Component(s) impacted

Footer

### Browser

Chrome, Microsoft Edge

### Carbon for IBM.com version

Canary

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Browserstack Automate

### Package

@carbon/ibmdotcom-react

### CodeSandbox example

https://automate.browserstack.com/dashboard/v2/builds/06deea8134cab157ea53ad6b92ff518c9329dcf0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
@jeffchew I don't know what's causing these errors, but I'm confident there's nothing wrong with the way the test is written.

In both cases, the tests properly asserted all 4 links that are loading from the storybook data [here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/react/src/components/Footer/__data__/footer-thin.json), and that data hasn't changed since February 2020.

```js
cy.get('[data-autoid="dds--footer-legal-nav"]')
      .find('li a')
      .each($link => {
        const url = $link.prop('href');
        expect(url).not.to.be.empty;
      });
```

The way the test fails it seems to think there's a fifth element matching the selector `[data-autoid="dds--footer-legal-nav"] li a`, but that shouldn't be present at all.

**Comment by IgnacioBecerra** [comment]
@andy-blum The fifth element seems to be the Cookie preferences link, which might not be rendering due to the Storybook and Cypress environment. I'd say that you could skip the fifth element in the test due to this, since the element might render the placeholder component containing no href to check.

**Comment by jeffchew** [comment]
Reopened this, looks like the issue still exists in Browserstack.

Taking a different approach to addressing the issue in this PR: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8147

**Comment by proeung** [comment]
@andy-blum Can you take a look at @jeffchew's comment?

**Comment by andy-blum** [comment]
@proeung I saw it - Is there something @jeffchew needs from me in #8147?

**Comment by proeung** [comment]
@andy-blum Looks like I missed the second sentence from Jeff's comment above, however, probably still good to have your review for PR: [#8147](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8147)

**Comment by andy-blum** [comment]
Looks like #8147 was merged in - can this issue be closed @jeffchew?
