### ISSUE TITLE
[Locale Modale]: Web Components - VO - Focus trapping not working in mobile

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#8146]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2393
- DPO consulting engineer: N/A

-----

### Description

Focus trapping is not working for the locale modal in mobile.

One thing to try is to change the sentinel nodes to button elements instead of anchor elements as done in: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8074. This would have to be done in the `carbon-web-components` modal component as locale modal is extending that.

https://user-images.githubusercontent.com/54281166/150870389-0e73f33a-66dc-4045-9021-2c20f3c6b98e.mov

### Component(s) impacted

Locale Modal

### Browser

Safari

### Carbon for IBM.com version

1.30.0-rc.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-locale-modal--default

### Package

@carbon/ibmdotcom-web-components

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment]
@annawen1 is this ticket needed for the same sprint as #8086?

**Comment by annawen1** [comment]
@andy-blum nope, this ticket is being treated separately! This one isn't going into this upcoming release so we can schedule this in for the next sprint.

**Comment by andy-blum** [comment]
Additional accessibility concerns regarding the locale modal:

## DDSRegionItem components are rendering links instead of buttons
<img width="433" alt="Screen Shot 2022-01-26 at 10 51 36 AM" src="https://user-images.githubusercontent.com/25532785/151197629-f7bf6cfa-f9f6-48e3-840c-5f72334d4db5.png">
- This is semantically wrong as clicking this item _does something_ rather than _goes somewhere_. 
- This has the unfortunate side effect in iOS voiceover of also never getting focused when VO reads the text, leading to disabled options getting read out but not being clickable. Rendering these as buttons would allow us to use the native `disabled` attribute on the button, preventing VO from ever reading it

## The focus trap doesn't navigate the same forwards as it does backwards
<img width="900" alt="Screen Shot 2022-01-26 at 10 54 34 AM" src="https://user-images.githubusercontent.com/25532785/151198537-ce85f2f8-f4e2-487b-8d5c-8f8cd640bde8.png">

Cycling the elements forwards and backwards should include all items, currently cycling forwards does not include the close button, which could lead visually imparied users to assume there is no close button.

This is coming from [the way we're collecting all focusable elements](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8089/files#diff-d7e1e2cc7aa32e854a58956a75e1969893fc24c3008fbc7c1d27f46111fccc85R168-R171) and always putting elements in the shadowRoot behind lightDOM children

## DDSLocaleSearch has some problems of its own
- On ios, the first focused item is the first item in the list. Cycling focus forward may lead users to think they have to navigate the entire list to get down to the bottom of the list. Ideally, the item getting focus would be the modal, allowing users to navigate forward through the close button, title, and search bar before getting to the list
- The search updates the list as users type, but that isn't communicated to the screen reader. As a user types in their search term, VO reads back the individual letter and if a pause is detected, will announce the entire word(s). But we should also communicate to users that the list of items has changed and how many options are there now with an `aria-live="polite"` region.

**Comment by proeung** [comment]
@andy-blum Since you already looked into this issue. Do you want to grab this one?
