### ISSUE TITLE
[Back To Top]: Web Components - The Back To Top icon is not loading in Mobile Safari on IOS

### ISSUE THREAD

**Issue by QALosey** [carbon-design-system/carbon-for-ibm-dotcom#8274]
### Description

Expected Results: 
  The Back To Top icon will appear on the page as the user scrolls down, and will direct the user back to the top of the page when selected.
 
Actual Results: 
  The Back To Top icon is not displaying in Mobile Safari on iOS.

### Component(s) impacted

Back to Top - Default
![Back To Top - iOS](https://user-images.githubusercontent.com/57540897/153958043-ab7ad271-0213-42fe-a0cd-3db8d04a7f1a.png)

### Browser

Safari

### Carbon for IBM.com version

v1.16.0-rc.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-back-to-top--default

### Steps to reproduce the issue (if applicable)

1. Navigate to https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-back-to-top--default in Mobile Safari on an iOS device
2. Select 'Canvas' to view the web component
3. Scroll down the page
4. Observe that the Back To Top icon does not display for the user

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@QALosey @annawen1 I'm not seeing the issue that you're describing here. I'm able to see the "Back to Top" button just fine within the mobile breakpoints and on my mobile device. I wonder if this is a false positive because you're testing this component using Storybook canvas view that might not be the best at rendering everything (see attached). Maybe try testing this again using the "open canvas new tab" button - https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/iframe.html?id=components-back-to-top--default?


https://user-images.githubusercontent.com/1815714/154154264-b32517b3-1724-4d3f-a4f9-21e5733b7cbf.mov

The only issue that I'm seeing is this odd padding issue that might be some sort of page overflow issue.
![Screen Shot 2022-02-15 at 4 40 22 PM](https://user-images.githubusercontent.com/1815714/154154279-ac3890b0-5903-4e65-936e-6e2ce2c3cc1d.png)

**Comment by QALosey** [comment]
@proeung The icon still doesn't display when I open the canvas in a new tab. This is on the iPhone XS Max running iOS 13.3.1.

**Comment by proeung** [comment]
@QALosey Can you verify if the "Back to Top" is showing up on the latest iOS `15.3.1`? https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/iframe.html?id=components-back-to-top--default If so, then we might need to discuss if we're supporting iOS versions are 2 behind. @jeffchew Let me know what you think.

**Comment by QALosey** [comment]
@proeung  Yeah, the OS seems to be the issue. I had Jerry verify it on his iPhone, and the "Back to Top" icon does show up in iOS 15.3.1. I'll have to check in and see about getting a newer iPhone or permission to update the one I have.

**Comment by proeung** [comment]
@kennylam Any thought about the above? ^

**Comment by proeung** [comment]
**Notes from the 02/21 "Carbon for IBM.com issue review with Innovation team" meeting:**
- According to our browsers support doc, we're only supporting the last 2 versions of a particular browser and devise OS.
- Since, this issue is happening on iOS v13, we're going to close out this issue since it's not covered within our support list, which will be updated to include the latest version of iOS 15 (https://w3.ibm.com/w3publisher/ibm-web-standards-external/standards-mandatory/browser-standards)
- @QALosey @raximkoron Please adjust your testing plan to include the last 2 versions of iOS.
