### ISSUE TITLE
[Tabs Extended]: Tabs that aren't open by default are unusable on iOS with VoiceOver

### ISSUE THREAD

**Issue by andy-blum** [carbon-design-system/carbon-for-ibm-dotcom#8357]
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2418
- DPO consulting engineer:

-----

### Description

When using iOS (iPad device) where `tabs-extended` is displayed with desktop design, with Voiceover, there is no way to change the active tab in the `tabs-extended` component. I think this may be related to using links in place of buttons, but regardless, the tabs component hides page content from screen reader users and prevents them from accessing content or links on hidden-by-default tabs.

For an example of how tabs should work per the W3, see [this codepen](https://codepen.io/andy-blum/full/KKyedzp)

### Component(s) impacted

tabs-extended, tabs-extended-with-media

### Browser

Safari

### Carbon for IBM.com version

Latest

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

carbon-for-ibmdotcom

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?id=components-tabs-extended--default

### Steps to reproduce the issue (if applicable)

Attempt to use tabs on iOS with VO active

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by RichKummer** [comment]
Hey @andy-blum , I tested this on iOS and I'm seeing that we're able to navigate between tabs with VoiceOver on. I noticed that when a tab is focused and if the tab has a tooltip, he focus area includes the tooltip even if the tab is not active yet. Is this the expected behavior for tabs with tooltips?

While Tab 1 is active but with Tab 2 selected, you can see the focus dips below the tab itself
![IMG_1192](https://user-images.githubusercontent.com/15643582/155614796-bb39b65d-7022-4ede-a8d5-19dedbb0e8d8.jpg)

Here Tab 2 is active and you can see that the focus is capturing the tooltip
![IMG_1193](https://user-images.githubusercontent.com/15643582/155615175-7dc12e5c-9e83-4cdc-978d-9450709f16c9.jpg)
