### ISSUE TITLE
[Cloud masthead]: extra spacing appears above the masthead

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#8450]
### Description

The `cloud-masthead` has extra spacing above it which needs to be removed.

![image](https://user-images.githubusercontent.com/909118/156626410-5b5dc044-73eb-456a-a94c-eaa925d11632.png)

### Component(s) impacted

`@ibmdotcom/web-components/cloud-masthead`

### Carbon for IBM.com version

v1.31.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

IBM Cloud

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/cloud

### Release date (if applicable)

Immediately

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
This issue is visible on the Drupal rendering side and not on the other content ecosystems within ibm.com because, within Drupal, we're adding extra styling to the `dds-cloud-masthead-container` and ` dds-masthead-container` because we needed it so it can be positioned nicely on the Drupal template side that includes v18/v19 nav bar and etc.
