### ISSUE TITLE
[Card group with static]: Update Storybook preview to include "Add CTA Link" boolean

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#8782]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2469
- DPO consulting engineer: N/A

-----

### Description

- While ensembling an example of the `Card Group` component using `Card with static` variant, I noticed that the `<dds-text-cta>` component that's being used is not aligned to the bottom of the card.
- This might be due to the fact that `<dds-text-cta>` might not be accounted for in the same height function that's defined in the `Card group` component.
-  `<dds-text-cta>` is used in place of `<dds-card-cta-footer>` because the static card variant doesn't enable the whole card to be clickable, except for the CTA link.

![Screen Shot 2022-05-03 at 10 34 26 AM](https://user-images.githubusercontent.com/1815714/166476860-53baa3dd-2568-483e-b507-11dcaf1c92d8.png)

### Component(s) impacted

Card Group

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### Carbon for IBM.com version

v.1.33

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/sharp-hugle-ylz0gg?file=/index.html

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
FYI, @oliviaflory @kennylam

**Comment by oliviaflory** [comment]
> Would it be okay if I open a PR to add links to the Card Group with Static and update the README doc, so that it's clear for folks using this component (see attached).

@proeung I'm ok with adding the example to storybook! 

1. I see in your example that the first card doesn't have a CTA, and the rest of the cards do have a CTA. Is that intentional that AEM might mix with and without CTA static cards like that?
2. Are you thinking of adding links to all the `Card group static` example or adding a knob to add the CTA like Card Static has? (I hope this makes sense!) I'd just like to make sure adopters can see examples with no CTAs and one with CTAs in the Card group static.

![card-static-knob May-04-2022 16-45-23](https://user-images.githubusercontent.com/45692622/166823054-9e937600-9c4e-4366-b269-f31d1e55dfc0.gif)


I'm also noticing we might have a bug in the `Card group with static` card story. There is a background change on hover, but a static card shouldn't have any interactive state until a CTA is added, and then only the CTA gets the interactive states. Not saying you need to fix this, but I think it's a bug!
![Screen Shot 2022-05-04 at 4 49 19 PM](https://user-images.githubusercontent.com/45692622/166823747-80fcdfb3-4692-4e60-b3e9-af33c3c58008.png)

**Comment by proeung** [comment]
> I see in your example that the first card doesn't have a CTA, and the rest of the cards do have a CTA. Is that intentional that AEM might mix with and without CTA static cards like that?

mmhh.. Not sure why the first card is not displaying the CTA link, but I'll check.

> Are you thinking of adding links to all the Card group static example or adding a knob to add the CTA like Card Static has? (I hope this makes sense!) I'd just like to make sure adopters can see examples with no CTAs and one with CTAs in the Card group static.

I was originally thinking of having the CTA text link show up by default in the `Card group static` preview, but happy to add the "Add CTA" boolean that displays the CTAs, if that's what you prefer.

**Comment by proeung** [comment]
@oliviaflory Any thought to my response above?

**Comment by oliviaflory** [comment]
Hi @proeung, thank you for the reminder.

I lean towards having the CTAs hidden by default due to the original intention of static cards being..static. The CTA was added after if I remember correctly. So if it's ok with you I'd love to have the boolean option with "Add CTA".
