### ISSUE TITLE
[LeadSpace]: Full width of the page

### ISSUE THREAD

**Issue by abhavya-tech** [carbon-design-system/carbon-for-ibm-dotcom#8847]
### The problem

The Leadspace provided by Carbon for ibm dot com does not cover the full width and also the gradient has been marked as compulsory. This makes the image look really out of space.

### The solution

There should be an option to have a full-width leadspace
There should be an option to remove the gradient or proper color can be given by the user for gradient. Just white and black gradient doesn't work for all images

### Application/website

JCL Code generator

### Business priority

High Priority = pressing release

### What time frame would this ideally be needed by (if applicable)

If this feature is available by end of May

### Examples

Lead space present in this website
https://www.ibm.com/cloud/analytics

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @abhavya-tech  thank you for the feature request!

> There should be an option to have a full-width leadspace

I believe there is already an option for a full-width lead space. 

However it does restrict the image width, this is to ensure the image maintains its visual integrity and doesn't stretch too far in wide viewports and does not warp or lose the visual focus of the image. The current implementation extends the theme background, which can be one of the light themes (white or gray 10) or one of the dark themes  (gray 90 or gray 100) depending on what works best with the image.

> There should be an option to remove the gradient or proper color can be given by the user for gradient. Just white and black gradient doesn't work for all images

The gradients are baked into the lead space in order to maintain the accessibility color contrast requirements for legible text. There are four color options as stated above one of the light themes (white or gray 10) or one of the dark themes  (gray 90 or gray 100) depending on what works best with the image.

**Examples:**

**White theme**
<img width="1241" alt="Screen Shot 2022-05-24 at 9 53 19 AM" src="https://user-images.githubusercontent.com/45692622/170053512-692cda65-0d00-4dea-9675-c59d9a6f034f.png">

---
**Gray 10 theme**
<img width="1159" alt="Screen Shot 2022-05-24 at 9 58 47 AM" src="https://user-images.githubusercontent.com/45692622/170053722-6de5c6b5-a31d-4d37-b80c-ae38a94ae5f6.png">

---
**Gray 90 theme**
<img width="1236" alt="Screen Shot 2022-05-24 at 9 53 28 AM" src="https://user-images.githubusercontent.com/45692622/170053578-5dcdc04c-4369-4bed-ac4c-1850e9b2295b.png">


**Gray 100 theme**
<img width="1154" alt="Screen Shot 2022-05-24 at 9 58 58 AM" src="https://user-images.githubusercontent.com/45692622/170053798-473b8c2d-bf28-4eb2-b515-a70b2b426f46.png">

**Comment by oliviaflory** [comment]
Closing, the lead space is following the design specs outlined by the Carbon for IBM.com team in order to maintain image visual integrity and accessibility requirements for color contrast.
