### ISSUE TITLE
[L0]: Authors report wrong L0

### ISSUE THREAD

**Issue by EAVilleda** [carbon-design-system/carbon-for-ibm-dotcom#9042]
### Description

This issue was raised by Allan & Amanda / allandb@br.ibm.com & amanda.dadamos@ibm.com

The list of pages below, doesn't show up the L0 (Let's create) as defined as we have in all other locales. 
This issue happens for specific locales. ae-en, hk-en, my-en, eg-en, sa-en, za-en, ph-en, id-en, th-en 
According to Edsa, the L0 menu items are determined in the dotcom translations repo. Please proceed with this change for these identified pages :
/cloud/aiops 
/cloud/amd 
/cloud/analytics 
/cloud/application-hosting 
/cloud/campaign/cloud-simplicity 
/cloud/decision-management 
/cloud/digital-assets-platform 
/cloud/edge-computing 
/cloud/education 
/cloud/gpu 
/cloud/healthcare 
/cloud/integration 
/cloud/intel 
/cloud/internet-of-things 
/cloud/migrate 
/cloud/partners/catalog-sell
/topics/industry-4-0
/topics/software-defined-data-center

### Component(s) impacted

Masthead https://www.ibm.com/standards/carbon/web-components/?path=/story/components-masthead--default

### Carbon for IBM.com version

v1.34.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

AEM (Marketing)

### Package

@carbon/ibmdotcom-web-components, @carbon/ibmdotcom-styles

### CodeSandbox example

No codesandbox avaiable

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@EAVilleda Thanks for submitting this issue, however, I just wanted to note that this type of masthead content updating request should go through the Translation team Trello board (https://trello.com/c/LsuQOAxh) so that we can have the proper review process and submit a PR for changes to go through. Nonetheless, it looks like @emyarod has already started a draft PR for the content changes (https://github.ibm.com/webstandards/ibm-dotcom-translations/pull/753). I'll have 
SHERYL Morgan and @kjwhitla take a look and review the changes and we'll have it merged/updated in the API endpoint.

**Comment by proeung** [comment]
@EAVilleda Content changes were made to the L0 Masthead (see - https://github.ibm.com/webstandards/ibm-dotcom-translations/pull/753). The latest API endpoints for the locales listed in this issue should now have the "Let's Create" link.
