### ISSUE TITLE
[CTA]: Add additional icons and CTA types

### ISSUE THREAD

**Issue by jwitkowski79** [carbon-design-system/carbon-for-ibm-dotcom#9170]
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2552

-----

### The problem

Based on Drupal data that was analyzed, there are additional CTA types that developers need to add in AEM. They are:

- Email
- Schedule
- Live chat
- Call
Screenshot with proposed icons attached
![Frame 196](https://user-images.githubusercontent.com/2040791/181087554-a6a8eaae-8bbc-4c7b-a939-9fafed341571.jpg)

### The solution

Based on discussions with Putra and Olivia, AEM should be in parody with the C4ibm.com library. In order for this to be accomplished, we will need to add the above listed CTA types to the C4IBM.com library. A design review and discussion happened with the C4ibm.com team on Wednesday 7/20/22 during office hours where the icons were approved to add to the library.

### Application/website

AEM Interfaces Team

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment]
@jwitkowski79 Thanks for adding this ticket!

@oliviaflory @kennylam Let me know when this feature request has been reviewed by your team. I can move this work into the next sprint, once we have an agreement on the solution.

**Comment by oliviaflory** [comment]
@jwitkowski79 Only question is if the chat icon should be called Live chat or Chat in the cta type.

@proeung this can be added into your sprint

**Comment by proeung** [comment]
@oliviaflory Thanks for the update, however, I think there's some follow-up engineering discussion that we need to have for these additional icons as they might be related to the Contact Module - https://www.ibm.com/standards/web/v19a-archive/components/contact-module/#call-to-actions.

@jeffchew @kennylam I think we need to bring this to the engineering office hour and determine if the Contact Module script is needed in order to support the initialization of the Email, Schedule, Live chat, and Call CTAs. I understand that this script is part of the v19a support, however, is there a Carbon package approach that exists today that we can leverage? If so, can you point me to the right dependency?

**Comment by kennylam** [comment]
> however, is there a Carbon package approach that exists today that we can leverage? If so, can you point me to the right dependency

@proeung No, nothing like that in the dotcom library. I don't think there is in the core Carbon packages either :disappointed:

**Comment by proeung** [comment]
@kennylam Bummer! So for this issue, what's your recommendation? Should we continue to use the v19 Contact Module script `data-ibm-contact=` attribute to define the type of CTAs (see [link](https://www.ibm.com/standards/web/v19a-archive/components/contact-module/#call-to-actions)) and note to adopters that they need to require this script in order to launch "[Book a consultation](https://www.ibm.com/standards/web/v19a-archive/components/contact-module/#book-a-consultation)" or other contact types?

**Comment by kennylam** [comment]
I was under the impression the Let's Talk module already had those icons, and that the contact module would show only the contact methods currently available, i.e. show `call` with the phone icon only if representatives were available. Did that change?

**Comment by proeung** [comment]
@kennylam I don't think that behavior has changed on the Contact Module side, but I think we're mostly talking about how this script will interact with a WC component like `<dds-button-cta>`. For instance, if the adopter were to use the following markup, would the button still launches the "Book a consultation" model?

```
<dds-button-cta 
    href="#" 
    cta-type="scheduler" 
    kind="primary" 
    data-ibm-contact="scheduler-link">
Schedule a consultation
</dds-button-cta>
```

Anywho, we can move this into the dev pipeline and get the additional icons added to the CTA types of the CTA component, but we'll need to note that they need to require this script in the header of their HTML page `<script src="https://www.ibm.com/common/digitaladvisor/cm-app/latest/cm-app.min.js" defer></script>` to get the model/lightbox to show up correctly.
