### ISSUE TITLE
[Masthead v2.0.0]: Optional CTA Design QA Feedback

### ISSUE THREAD

**Issue by proeung** [carbon-design-system/carbon-for-ibm-dotcom#9341]
**Engineering info:**  
- JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2586
- JIRA Epic: https://jsw.ibm.com/browse/AEMSITES-146

-----

### Description

- [ ]  Optional/Ghost CTA is not rendering within the mobile slide menu (see attached)

![Screen Shot 2022-09-07 at 1 11 32 PM](https://user-images.githubusercontent.com/1815714/188939027-63b8fc8e-798f-49dd-bec4-b6e72e248aa3.png)

- [ ] Divider line is missing between the profile icon and the optional CTA

![Screen Shot 2022-09-07 at 1 14 08 PM](https://user-images.githubusercontent.com/1815714/188939444-6ddc7da8-dac8-45c2-939d-f77945d6f0f4.png)

See Storybook environment - https://carbon-design-system.github.io/carbon-for-ibm-dotcom/masthead-v2/web-components/?path=/story/components-masthead--with-cloud-data

### Additional information
- **Overview and scope of the engineering work should be included in the linked epic (#9208)**

### Design Specs
- Figma mockup - https://www.figma.com/file/35JfN0Sg4ltIIjM7jBDKMk/Navigation?node-id=1970%3A108827

**Comment by jwitkowski79** [comment]
@proeung @jkaeser Hello! Adding few other issues that we found while design QAing the Masthead on a call this afternoon. Adding them here but feel free to break these out into separate ticket since the original ticket was already merged.

### Utility nav
- Can we make sure that the login/my ibm goes to the correct place? I know that this a prototype but just wanted to double check that
- Same as above for the chat. It should trigger UMX (again..knowing that this is a prototypw and it may not work in this but should work in the final product)

### Divider lines
The vertical divider line should only fade at the bottom if there's scrolling enabled. See screenshot:
![divider_line](https://user-images.githubusercontent.com/2040791/188957137-b44cf38c-4c52-4a49-8a01-d584e8ab0e53.png)

### Scrolling
There should be independent scrolling functionality between the left and right menu. Right now, everything scrolls as a whole. See attached screenshot of how this is supposed to work:
![Screen Shot 2022-09-07 at 3 03 58 PM](https://user-images.githubusercontent.com/2040791/188957461-d41394b0-ebc2-4d5a-bdc0-da1c807fbcc9.png)

### Focus
Why trying to design QA this, we noticed that the entire menu closes on focus. We noticed that the original masthead does this too. Is there a better way to handle this? It's more of an annoyance, functionality quirk but understand if it needs to be this way for accessibility purposes.

**Comment by jkaeser** [comment]
Thanks for the feedback, @jwitkowski79! I'm going to break each of these issues into their own tickets.

**Comment by proeung** [comment]
@jkaeser Let's review some of these items because the "independent scrolling functionality" one to me might be considered out of scope for `Masthead v2.0.0` (Phase 1). 

As for the testing of the utility buttons, I believe this is part of the adoption/integration testing work that we'll be conducting on the AEM and Drupal sides (https://jsw.ibm.com/browse/ADCMS-2518) as these platforms have the proper DDO script to initialize the UMX contact and ProfileAPI.

**Comment by jkaeser** [comment]
> @jkaeser Let's review some of these items because the "independent scrolling functionality" one to me might be considered out of scope for `Masthead v2.0.0` (Phase 1).

@proeung Yep, I put each of these in the Phase 2 epic. See https://jsw.ibm.com/browse/ADCMS-2590 for example.

> As for the testing of the utility buttons, I believe this is part of the adoption/integration testing work that we'll be conducting on the AEM and Drupal sides (https://jsw.ibm.com/browse/ADCMS-2518) as these platforms have the proper DDO script to initialize the UMX contact and ProfileAPI.

Right, I wanted to ask you about that. I hadn't made a ticket for it yet since I was under the impression that these were going to be handled during integration into the CMS platforms. Sounds like we're on the same page!
