### ISSUE TITLE
[Lead space] design study

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9664]
### Brief / Overview
There are a number of issues with the lead space specs. We need to review the existing specs, identify gaps and recommend updates. Based on the items identified in the design research we need to explore:

### Things to explore
**Type tokens**
- [ ] Test swapping semi-bold text to light (display-01, expressive-heading-05)
- [ ] Need to identify text length
- [ ] Consider if it should be a knob or total swap
- [ ] Various content scenarios:
   - [ ] Only Headline
   - [ ] Headline + Single CTA 
   - [ ] Headline + secondary copy

**Image size**
- [ ] Define image sizes for adopters
- [ ] Full width photo w gradient
- [ ] Full width illustration w "safe area" for images considering text
- [ ] All breakpoints
   - [ ] Sm (320–671px)
   - [ ] Md (672–1055px)
   - [ ] Lg (1056–1311px)
   - [ ] Xlg (1312–1583px)
   - [ ] Max (1584 +)

**Size variations**
- [ ] Talk to Jen W about what sizes of lead space they are using in AEM
- [ ] Can we drop any of the current sizes? Are they too similar?

### Additional Information
- **See the epic (#?epic issue?) for the overarching descriptions of the work.**
- [Box folder]()
- [Figma Sketch import](https://www.figma.com/file/qUf86S5SSxf8WuLZ638oqa/Layout-component--lead-space--left-aligned--design-specs--v2.1?node-id=5%3A20266&t=JpjxN3OnP8HPCJMC-1)

### Acceptance Criteria
- [ ] Design explorations have been shared with Carbon design
- [ ] Design direction(s) has been identified, reviewed, and approved for the final design phase
- [ ] The next story has been updated with the design direction

**Comment by oliviaflory** [comment]
Review Dec 13
**Image**
- Check with dev if single asset for lg, xlg, max breakpoints
- And how image is pinned (or not) at the different breakpoints.
- Single diagram for desktop image asset of max breakpoint image 

**Type**
- Options for Display-01 AND Expressive-heading-05
- Option to change colors

**Comment by RichKummer** [comment]
### Engineering Mtg 12/14

********************************You can currently pass in an image asset for each breakpoint. If you wanted to only use one, use the default which is @max.********************************

- `@max` - `@lg:` designer/developer _can_ provide an image background asset for each breakpoint. 
- You can define a "default" image asset, which ideally would be `@max` to have the highest resolution and avoid stretching the image.

**How does the image background scale in `lead space`?**

- It uses `cover` → it’ll do everything it can to not crop the image. It functions closest to a `centered` image, rather than pinned to one side.

**What does ‘[cover](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size)’ mean?**

- `background-size: cover` in CSS scales the image (while preserving its ratio) to the smallest possible size to fill the container (that is: both its height and width completely *cover* the container), leaving no empty space.
    - If the proportions of the background differ from the element, the image is cropped either vertically or horizontally.

**Comment by RichKummer** [comment]
## Dot grid explo
[Codepen exploration](https://codepen.io/RichKummer/pen/zYLzRWq?editors=1111) for programmatic dot grid
