### ISSUE TITLE
[Component]: multi-select

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#9996]
Notes:
- option items spacing incorrect

**Comment by emyarod** [comment]
the item spacing may be linked to a larger issue

<img width="347" alt="image" src="https://user-images.githubusercontent.com/8265238/220979183-8e4bd540-ce15-47b0-8b23-6f381f766a62.png">

in the multiselect, the option labels are misaligned because the container height seems to be larger than expected

although it doesn't appear to be misaligned in combobox or dropdown, examining the option elements shows that the same issue occur there as well

<img width="352" alt="image" src="https://user-images.githubusercontent.com/8265238/220979683-da704fec-92ac-4314-9bd5-a294a892b786.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/8265238/220979506-e8b825b6-5140-4acd-b41e-85c5434f5dcc.png">

from what I can tell, this is due to the CSS reset not properly being applied and the `box-sizing` values being the default `content-box` rather than the expected `border-box`
